{
  "pageTitle": "Claude Code Usage Dashboard",
  "heading": "Claude Code Token Usage",
  "subModelsHtml": "Only <strong>Claude</strong> models (<code>claude-*</code>) — no <code>&lt;synthetic&gt;</code> lines.",
  "langLabel": "Language",
  "ariaLangGroup": "Choose language",
  "liveFilesAria": "Scanned JSONL files",
  "livePanelAria": "Live panel: scanned JSONL, Anthropic outages, extension updates",
  "liveFilesHint": "Click \u201cLive\u201d to open or close this panel. Each line: source \u00b7 path (~ = home on this machine).",
  "liveFilesHead0": "Scanned JSONL",
  "liveFilesHeadN": "Scanned JSONL ({n})",
  "scanStill": "Scan still running…",
  "noJsonlList": "No .jsonl under configured scan roots (see data source / CLAUDE_USAGE_EXTRA_BASES).",
  "sseDisconnected": "Disconnected — retrying…",
  "liveTriggerScanning": "Live — scan running",
  "liveTriggerZero": "0 JSONL files",
  "liveTriggerMany": "{n} JSONL — click to open the Live panel",
  "liveOutageHead": "Outages (status.claude.com)",
  "liveOutageEmpty": "No outage entries in the current range.",
  "liveExtHead": "Extension updates (Claude Code)",
  "liveExtEmpty": "No extension version changes in the range.",
  "liveExtOpenAria": "Open extension update details",
  "metaShellReady": "Layout ready — the page structure is already here. A live scan streams log data; charts fill in as days are parsed (you are not waiting for a finished on-disk day cache).",
  "metaDetailsSummaryDefault": "Meta & data sources",
  "dayPickerScanning": "Scan running…",
  "dayPickerNoData": "No day selectable yet",
  "metaScanning": "Scanning ~/.claude/projects in the background… Updates via SSE. Files read in small batches.",
  "metaForensicScanning": "Forensic — scan running…",
  "metaForensicNoteFirst": "First run after server start; then every {sec}s in the background.",
  "liveWaitData": "Live — waiting for data…",
  "metaNoFiles": "No data: 0 .jsonl files in scan roots (~/.claude/projects and CLAUDE_USAGE_EXTRA_BASES if set). Without matching logs, cards and tables stay empty.",
  "metaNoUsage": "No daily values: read {files} file(s) but no usage lines with model claude-*.",
  "forensicSummaryNoData": "Forensic (token_forensics) — no data",
  "metaParsed": "Parsed {files} log files | Last update: {time} | Auto-refresh every {sec}s",
  "metaParsedInProgress": "Loading {done}/{total} log files | Last update: {time} | Auto-refresh every {sec}s",
  "metaChartsHint": "| Cards & table: selected day. Main charts: toggle \u00bbAll days / 24 h\u00ab below.",
  "metaChartsHintHourly": "24h mode: one calendar day by hour; token bars split by API events/hour (estimate).",
  "mainChartsScopeLabel": "Main charts:",
  "mainChartsScopeAria": "Charts: full date range or hours of the selected day",
  "mainChartsScopeTimeline": "All days",
  "mainChartsScopeHourly": "24 h (picked day)",
  "chartDailyTokenHourly": "Tokens/h (estimated)",
  "chartCacheRatioHourly": "Cache:output/h (estimated)",
  "chartOutPerHourHourly": "API events per hour",
  "chartSubCachePctHourly": "Session signals per hour",
  "chartTooltipHourlyTokenEst": "Token rows: day total \u00d7 (events this hour / day event sum).",
  "chartHourlyApiEventsLabel": "API events",
  "metaDetailsSummaryLine": "{files} log files · every {sec}s — expand for notes & status",
  "metaSummaryScanning": "Scanning… — expand",
  "metaDetailsScanProgress": "{done}/{total} log files · every {sec}s — loading live",
  "metaScanningExpanded": "Scan: read {done}/{total} log files (refresh every {sec}s). Charts appear once data exists — not final yet.",
  "metaSummaryNoFiles": "No .jsonl under scan roots — expand",
  "metaSummaryNoUsage": "No usage in {files} file(s) — expand",
  "calTodaySuffix": " — calendar today",
  "zeroLogsSuffix": " (0 in logs)",
  "dayPickerHintZero": "Calendar today: 0 tokens in logs — pick another day with usage.",
  "limitSourceTooltip": "Anthropic / Claude Code enforce session and rate limits; JSONL mostly shows successful API usage. Hit limit counts lines matching typical limit/error patterns.",
  "dailyDetailPrefix": "Daily detail — ",
  "dailyDetailClearHost": "All hosts",
  "dailyDetailHostRowTitle": "Click: this host only in daily detail",
  "dailyDetailFilteredRowTitle": "Click: show all hosts again",
  "forensicHostFilterLabel": "Source:",
  "forensicHostFilterAll": "All hosts",
  "forensicHostFilterAria": "Filter forensic charts by JSONL source (host)",
  "forensicHostFilterHint": "Bars/line use tokens, session signals and hit limits for \u201c{host}\u201d only. Outage hours stay the calendar day from Anthropic (status.claude.com), not attributable to one machine.",
  "forensicTooltipHostHitScope": "Hit-limit bars: {host} only. Lines below (peak, implied budget, note) refer to the full day across all sources.",
  "forensicSignalsTooltipOutageDayScope": "Outage segment: whole calendar day (Anthropic), not host-specific.",
  "forensicSummaryHostSuffix": " \u00b7 Source: {host}",
  "forensicClientHintNone": "No forensic flag (for this source).",
  "forensicClientHintCache": "Cache read \u2265500M \u2014 possible heavy session/cache signal.",
  "forensicClientHintHit": "JSONL: rate/limit/429-like lines for this source.",
  "forensicClientHintPeak": "Much lower tokens vs peak day ({peak}) with substantial output/calls \u2014 same heuristic as token_forensics.",
  "reportBtnTitle": "Generate forensic report as Markdown",
  "liveConnected": "Live ({time})",
  "dayPickerLabel": "Cards & table (pick day)",
  "dayPickerAria": "Day for cards and daily detail",
  "cardDayOutput": "Day output",
  "cardDayCacheRead": "Day cache read",
  "cardCacheOutSub": "Cache:Out {ratio}x",
  "cardDayTotal": "Day total",
  "cardCallsActiveSub": "{calls} calls, {hours}h active",
  "cardHitDay": "Hit limit (day)",
  "cardHitDaySub": "JSONL lines suggesting limits/429 that day",
  "cardHitAll": "Hit limit (all days)",
  "cardHitAllSub": "Sum across all days",
  "cardOverhead": "Day overhead",
  "cardOverheadSub": "tokens per output token",
  "cardPeak": "Peak day total",
  "cardPeakSub": "{date} (highest Claude usage in logs)",
  "cardAllOut": "All-time output",
  "cardAllOutSub": "{days} days with usage",
  "cardAllCache": "All-time cache read",
  "cardAllCacheSub": "{pct} of total",
  "cardSessionSignals": "Session signals (JSONL)",
  "cardSessionSignalsSub": "continue {c} · resume {r} · retry {y} · interrupt {i} — heuristic text match",
  "chartSessionSignalsTitle": "Session signals in logs (per day)",
  "chartSessionSignalsBlurb": "Counts of JSONL lines matching --continue/--resume, retry/429 patterns, or interrupt/cancel (heuristic; not API truth).",
  "sigContinue": "continue",
  "sigResume": "resume",
  "sigRetry": "retry",
  "sigInterrupt": "interrupt",
  "cardHostParen": " (day)",
  "cardHostSub": "{out} out · {calls} calls · HitLim {hit}",
  "fcForensicDay": "Forensic (selected day)",
  "fcImpl": "Impl. cap @90%",
  "fcImplSub": "total/0.9 (illustrative, not Claude UI 90%/100%)",
  "fcBudget": "Budget reduction",
  "fcBudgetSub": "peak / (limitDay/0.9) — peak & limit auto-detected (token_forensics.js)",
  "forensicSummaryLine": "Forensic — {pick}: {fc} | Impl@90%: {impl} | Budget ~{bud}x | Peak {peak}",
  "chartDailyToken": "Daily token consumption",
  "chartCacheRatio": "Cache:output ratio (lower = more efficient)",
  "chartHostTitle": "Total tokens per day by host (stacked)",
  "chartHostBlurb": "Sum of input+output+cache read+cache creation per host. Bar height matches the full day (same idea as daily token chart).",
  "chartOutPerHour": "Output per active hour",
  "chartSubCachePct": "Subagent cache % of total cache",
  "chartTooltipSubCacheOfDay": "of day cache read",
  "chartTooltipSubCacheStackTotal": "Bar height ≈ day sub-cache share: {pct}%",
  "chartDS_cacheRead": "Cache read",
  "chartDS_output": "Output",
  "chartDS_cacheCreate": "Cache create",
  "chartLineCacheOut": "Cache:output",
  "chartTooltipCoDay": "C:O (day): {ratio}x",
  "chartTooltipOutCacheDay": "Output {out} · Cache read {cache}",
  "chartTooltipCoHostLine": "{host}: C:O {ratio}x",
  "chartOutPerHLabel": "Output/h",
  "hostStackFooter": "Sum (all hosts): ",
  "forensicDS_hitLimit": "Hit limit (JSONL lines)",
  "forensicDS_score": "Forensic score (3=? · 2=HIT · 1=<<P)",
  "forensicAxisHit": "Hit limit (red)",
  "forensicAxisCounts": "JSONL lines (signals + hits)",
  "forensicAxisForensic": "Forensic",
  "serviceAxisHours": "Hours",
  "serviceTooltipSessionSigHourNote": "Per hour: retry \u2192 red, interrupt \u2192 yellow (JSONL timestamp); continue/resume stay in clean work. Stacked bars count only hours with token usage.",
  "serviceTooltipSlideoutHint": "Extension releases, model change, outage report & forensic: click \u25b2 / \u25c7 or an entry in the Live panel \u2192 right slideout.",
  "tooltipVsPeak": "vs peak: ",
  "tooltipImpl90": "Impl@90%: ",
  "scanSourcesPrefix": "Scan sources: ",
  "statePathsTitle": "Local dashboard files (~/.claude):",
  "statePathDay": "Day cache: ",
  "statePathTodayIndex": "JSONL today index (mtime): ",
  "statePathReleases": "GitHub releases: ",
  "statePathMarketplace": "Marketplace versions: ",
  "statePathOutage": "Outage cache: ",
  "githubTokenLabel": "GitHub PAT (this browser tab only, sessionStorage):",
  "githubTokenSave": "Save",
  "githubTokenClear": "Clear",
  "githubTokenRefreshReleases": "Fetch releases",
  "githubTokenSavedLine": "GitHub PAT (saved) — value is not shown.",
  "githubTokenHint": "The token is sent only to this dashboard as the X-GitHub-Token header; the server calls the GitHub API (not your browser). A classic PAT is enough for public release metadata. Closing the tab clears it.",
  "githubTokenSaved": "Saved.",
  "githubTokenStoredPersistent": "PAT active (this tab only). No full JSONL rescan triggered.",
  "githubTokenCleared": "Cleared. The server falls back to GITHUB_TOKEN/GH_TOKEN if set.",
  "githubReleasesRefreshOk": "Release refresh started (background).",
  "githubReleasesRefreshFail": "Release refresh failed (network or admin token).",
  "marketplaceRefreshLabel": "VS Marketplace (extension versions)",
  "marketplaceRefreshOk": "Marketplace fetch started (background; check server log). SSE/timeline update when done.",
  "marketplaceRefreshFail": "Marketplace fetch failed (network, timeout, or 401 admin token).",
  "forensicChartTitle": "Forensic & hit limit per day",
  "forensicChartBlurbHtml": "One <strong>stacked bar</strong> per day: <strong>hit-limit</strong> JSONL line counts. <strong style=\"color:#f59e0b\">Line</strong> = forensic score (3=? \u00b7 2=HIT \u00b7 1=&lt;&lt;P). Below: <strong>session signals per day</strong> (stacked, <strong>outage hours</strong> as the <strong>top</strong> segment) + <strong>cache read</strong> as a line \u2014 see the next chart.",
  "forensicSignalsChartTitle": "Session signals & outage (stacked) + cache read",
  "forensicSignalsBlurbHtml": "Per <strong>day</strong>: <strong>bottom \u2192 top</strong> continue, resume, retry, interrupt, then <strong>outage (h)</strong> as the <strong>top</strong> bar segment (so it does not sit <em>under</em> a huge interrupt slice). Outage <strong>bar height is scaled</strong> (hours vs. JSONL counts); the <strong>tooltip</strong> shows real hours. <strong>Purple line</strong> = cache read (separate right scale) \u2014 same-day heuristic vs. interrupts/outage, not proof of cause. Tooltip adds output/cache and C:O.",
  "forensicSignalsAxisLines": "Signals + outage (h, bar scaled)",
  "forensicSignalsAxisOutage": "Outage (h)",
  "forensicSignalsAxisCacheRead": "Cache read (tokens)",
  "forensicDS_continueStack": "continue",
  "forensicDS_resumeStack": "resume",
  "forensicDS_retryStack": "retry",
  "forensicDS_interruptStack": "interrupt",
  "forensicDS_outageHoursDay": "Outage (h)",
  "forensicSignalsTooltipStackFooter": "Bars: signals/day, outage on top (tooltip = real h); purple line = cache read (own scale).",
  "unifiedAxisTokens": "Tokens",
  "unifiedChartTitle": "Token Budget & Outage Impact",
  "serviceChartTitle": "Service Impact: Work vs. Outage",
  "mainChartsSkelHint": "Placeholder \u2014 token charts render here as soon as usage data is ready (no need to wait for a full cache refresh).",
  "serviceBlurb": "<strong style=\"color:rgba(59,130,246,0.8)\">Blue</strong> = clean work. <strong style=\"color:rgba(239,68,68,0.8)\">Red</strong> = hours with API/server stress: declared outage <strong>or</strong> JSONL <code>retry</code> bucketed by the log entry\u2019s clock hour (not a single lump for the whole day). <strong style=\"color:rgba(251,191,36,0.8)\">Yellow</strong> = client outage <strong>or</strong> JSONL <code>interrupt</code> in that hour. <strong style=\"color:rgba(107,114,128,0.6)\">Gray</strong> = outage without work in those hours. Continue/resume still count as clean hours. <strong>Stacked bars</strong> count only hours with real token usage (pure session signals alone do not add bar hours). Daily signal totals (stacked): <strong>Forensic</strong> section, chart below. <strong style=\"color:#8b5cf6\">Purple line</strong> = cache read (right scale). <strong style=\"color:#22d3ee\">\u25c7</strong> / <strong style=\"color:#4ade80\">\u25b2</strong> = model vs. extension day (click \u2192 <strong>slideout</strong>: release notes, outage report, forensic). <strong>Tooltip</strong> only bar/token summary; <strong>Live</strong> panel: outage list & compact extension list.",
  "serviceTooltipSessionSig": "JSONL lines (c / r / retry / interrupt)",
  "serviceDS_cleanWork": "Clean work",
  "serviceDS_affectedServer": "Work during API outage (retries)",
  "serviceDS_affectedClient": "Work during client bug (no token impact)",
  "serviceDS_affectedWork": "Work during outage",
  "serviceDS_outageOnly": "Outage (no work)",
  "thinkingNote": "\u26a0 Thinking tokens (internal reasoning) do not appear in the API response and are not counted here. They likely count against the session budget.",
  "tableCols": "Date|Output|Cache read|C:O|Overhead|Total|Calls|Hours|Hit limit|Sub%|Sub cache%|Out/h",
  "metaScanError": "Scan error: {msg}",
  "reportBtn": "Forensic Report",
  "reportTitle": "Forensic Report (Markdown)",
  "reportCopy": "Copy",
  "reportDownload": "Download .md",
  "reportCopied": "Copied!",
  "reportNoData": "No data — scan must complete first.",
  "outageChartTitle": "Outage Windows (status.claude.com)",
  "outageChartBlurbHtml": "Bars show outage time windows (UTC). <strong style=\"color:#f97316\">Orange</strong> = major, <strong style=\"color:#ef4444\">Red</strong> = critical, <strong style=\"color:#facc15\">Yellow</strong> = minor. Hover for details.",
  "outageDS_spans": "Outage window",
  "outageAxisHour": "Hour",
  "outageTotal": "total outage",
  "statusPending": "Status…",
  "statusPendingTip": "Loading Anthropic status…",
  "statusOutage": "Outage!",
  "statusOutageTip": "Active outage reported at Anthropic (status.claude.com)",
  "statusIncident": "Incident",
  "statusIncidentTip": "An incident was reported at Anthropic today (already resolved)",
  "statusOk": "OK",
  "statusOkTip": "No current incidents at Anthropic (status.claude.com)",
  "tooltipOutage": "Outage: ",
  "tooltipModelAdded": "Model added: ",
  "tooltipModelRemoved": "Model removed: ",
  "forensicDS_modelChange": "Model change",
  "forensicDS_outageHours": "Outage (h)",
  "serviceDS_versionChange": "Extension update",
  "tooltipVersionUpdate": "Extension: ",
  "serviceTooltipReleaseClock": "Marketplace/release time: ",
  "serviceTooltipReleaseUtc": "booked on UTC day (same as JSONL date): ",
  "serviceTooltipReleaseLocal": "local calendar day (this machine): ",
  "updateSlideoutClose": "Close",
  "updateDotAria": "Extension update: show details",
  "modelDotAria": "Model change: show details",
  "modelSlideoutHeading": "Model change",
  "modelSlideoutNoDetail": "No model-change details for this day.",
  "updateSlideoutHeading": "Extension update",
  "updateSlideoutNoDetail": "No version details for this day.",
  "updateSlideoutHighlights": "Release notes (excerpt)",
  "updateSlideoutHighlightsEmpty": "No excerpt yet: after each scan the server backfills missing releases via HTTPS into ~/.claude/claude-code-releases.json — wait for the live update, then open this panel again. Or open GitHub:",
  "updateSlideoutGithubReleases": "GitHub releases",
  "updateSlideoutStatusHeading": "Anthropic status / outages (this day)",
  "updateSlideoutOutageHoursLine": "Outage time: {total} h total (server {srv} h \u00b7 client {cli} h)",
  "updateSlideoutOutageIncidents": "Incidents (status.claude.com)",
  "updateSlideoutOutageSpans": "Time windows (UTC, calendar day)",
  "updateSlideoutLikelyHit": "Note: many hit-limit lines in JSONL \u2014 possible overlap with outages (heuristic).",
  "updateSlideoutIncidentStart": "Started",
  "updateSlideoutIncidentResolved": "Resolved",
  "updateSlideoutIncidentOngoing": "ongoing / unknown",
  "updateSlideoutForensicHeading": "Forensic (summary)",
  "serviceTooltipReleaseGithubHint": "GitHub (release pages):",
  "timelineTitle": "Work & Outage Timeline (0\u201324h)",
  "timelineBlurbHtml": "<strong style=\"color:rgba(59,130,246,0.7)\">Blue</strong> = work window (first to last active hour, opacity = intensity). <strong style=\"color:rgba(239,68,68,0.7)\">Red</strong> = Anthropic outage. <strong style=\"color:#22d3ee\">\u25c7</strong> = model change. Overlap = outage during work.",
  "timelineDS_work": "Work window",
  "timelineDS_outage": "Outage (status.claude.com)",
  "timelineAxisHour": "Time of day (UTC)"
}
