{
  "pageTitle": "Claude Code Usage Dashboard",
  "heading": "Claude Code Token Usage",
  "subModelsHtml": "Only <strong>Claude</strong> models (<code>claude-*</code>) — no <code>&lt;synthetic&gt;</code> lines.",
  "langLabel": "Language",
  "ariaLangGroup": "Choose language",
  "liveFilesAria": "Scanned JSONL files",
  "livePanelAria": "Live panel: scanned JSONL, Anthropic outages, extension updates",
  "liveFilesHint": "Click “Live” to open or close this panel. Each line: source · path (~ = home on this machine).",
  "liveFilesHead0": "Scanned JSONL",
  "liveFilesHeadN": "Scanned JSONL ({n})",
  "scanStill": "Scan still running…",
  "noJsonlList": "No .jsonl under configured scan roots (see data source / CLAUDE_USAGE_EXTRA_BASES).",
  "sseDisconnected": "Disconnected — retrying…",
  "liveTriggerScanning": "Live — scan running",
  "liveTriggerZero": "0 JSONL files",
  "liveTriggerMany": "{n} JSONL — click to open the Live panel",
  "liveOutageHead": "Outages (status.claude.com)",
  "liveOutageEmpty": "No outage entries in the current range.",
  "liveExtHead": "Extension updates (Claude Code)",
  "liveExtEmpty": "No extension version changes in the range.",
  "liveExtOpenAria": "Open extension update details",
  "metaShellReady": "Layout ready — the page structure is already here. A live scan streams log data; charts fill in as days are parsed (you are not waiting for a finished on-disk day cache).",
  "metaDetailsSummaryDefault": "Meta & data sources",
  "dayPickerScanning": "Scan running…",
  "dayPickerNoData": "No day selectable yet",
  "metaScanning": "Scanning ~/.claude/projects in the background… Updates via SSE. Files read in small batches.",
  "metaForensicScanning": "Forensic — scan running…",
  "metaForensicNoteFirst": "First run after server start; then every {sec}s in the background.",
  "liveWaitData": "Live — waiting for data…",
  "metaNoFiles": "No data: 0 .jsonl files in scan roots (~/.claude/projects and CLAUDE_USAGE_EXTRA_BASES if set). Without matching logs, cards and tables stay empty.",
  "metaNoUsage": "No daily values: read {files} file(s) but no usage lines with model claude-*.",
  "forensicSummaryNoData": "Forensic (token_forensics) — no data",
  "metaParsed": "Parsed {files} log files | Last update: {time} | Auto-refresh every {sec}s",
  "metaParsedInProgress": "Loading {done}/{total} log files | Last update: {time} | Auto-refresh every {sec}s",
  "metaChartsHint": "| Cards & table: selected day. Main charts: toggle »All days / 24 h« below.",
  "metaChartsHintHourly": "24h mode: one calendar day by hour; token bars split by API events/hour (estimate).",
  "mainChartsScopeLabel": "Main charts:",
  "mainChartsScopeAria": "Charts: full date range or hours of the selected day",
  "mainChartsScopeTimeline": "All days",
  "mainChartsScopeHourly": "24 h (picked day)",
  "chartDailyTokenHourly": "Tokens/h (estimated)",
  "chartCacheRatioHourly": "Cache:output/h (estimated)",
  "chartOutPerHourHourly": "API events per hour",
  "chartSubCachePctHourly": "Session signals per hour",
  "chartTooltipHourlyTokenEst": "Token rows: day total × (events this hour / day event sum).",
  "chartHourlyApiEventsLabel": "API events",
  "metaDetailsSummaryLine": "{files} log files · every {sec}s — expand for notes & status",
  "metaSummaryScanning": "Scanning… — expand",
  "metaDetailsScanProgress": "{done}/{total} log files · every {sec}s — loading live",
  "metaScanningExpanded": "Scan: read {done}/{total} log files (refresh every {sec}s). Charts appear once data exists — not final yet.",
  "metaSummaryNoFiles": "No .jsonl under scan roots — expand",
  "metaSummaryNoUsage": "No usage in {files} file(s) — expand",
  "calTodaySuffix": " — calendar today",
  "zeroLogsSuffix": " (0 in logs)",
  "dayPickerHintZero": "Calendar today: 0 tokens in logs — pick another day with usage.",
  "limitSourceTooltip": "Anthropic / Claude Code enforce session and rate limits; JSONL mostly shows successful API usage. Hit limit counts lines matching typical limit/error patterns.",
  "dailyDetailPrefix": "Daily detail — ",
  "dailyDetailClearHost": "All hosts",
  "dailyDetailHostRowTitle": "Click: this host only in daily detail",
  "dailyDetailFilteredRowTitle": "Click: show all hosts again",
  "forensicHostFilterLabel": "Source:",
  "forensicHostFilterAll": "All hosts",
  "forensicHostFilterAria": "Filter forensic charts by JSONL source (host)",
  "forensicHostFilterHint": "Bars/line use tokens, session signals and hit limits for “{host}” only. Outage hours stay the calendar day from Anthropic (status.claude.com), not attributable to one machine.",
  "forensicTooltipHostHitScope": "Hit-limit bars: {host} only. Lines below (peak, implied budget, note) refer to the full day across all sources.",
  "forensicSignalsTooltipOutageDayScope": "Outage segment: whole calendar day (Anthropic), not host-specific.",
  "forensicSummaryHostSuffix": " · Source: {host}",
  "forensicClientHintNone": "No forensic flag (for this source).",
  "forensicClientHintCache": "Cache read ≥500M — possible heavy session/cache signal.",
  "forensicClientHintHit": "JSONL: rate/limit/429-like lines for this source.",
  "forensicClientHintPeak": "Much lower tokens vs peak day ({peak}) with substantial output/calls — same heuristic as token_forensics.",
  "reportBtnTitle": "Generate forensic report as Markdown",
  "liveConnected": "Live ({time})",
  "dayPickerLabel": "Cards & table (pick day)",
  "dayPickerAria": "Day for cards and daily detail",
  "cardDayOutput": "Day output",
  "cardDayCacheRead": "Day cache read",
  "cardCacheOutSub": "Cache:Out {ratio}x",
  "cardDayTotal": "Day total",
  "cardCallsActiveSub": "{calls} calls, {hours}h active",
  "cardHitDay": "Hit limit (day)",
  "cardHitDaySub": "JSONL lines suggesting limits/429 that day",
  "cardHitAll": "Hit limit (all days)",
  "cardHitAllSub": "Sum across all days",
  "cardUptime": "Service Uptime",
  "cardUptimeSub": "across {days} days (major_outage only)",
  "cardServiceQuality": "Service Quality",
  "cardServiceQualitySub": "across {days} days (crit+major+minor)",
  "cardOverhead": "Day overhead",
  "cardOverheadSub": "tokens per output token",
  "cardPeak": "Peak day total",
  "cardPeakSub": "{date} (highest Claude usage in logs)",
  "cardAllOut": "All-time output",
  "cardAllOutSub": "{days} days with usage",
  "cardAllCache": "All-time cache read",
  "cardAllCacheSub": "{pct} of total",
  "cardSessionSignals": "Session signals (JSONL)",
  "cardSessionSignalsSub": "continue {c} · resume {r} · retry {y} · interrupt {i} — heuristic text match",
  "tokenStatsSummary": "{date} — {out} output · {cache} cache · {overhead} overhead",
  "chartSessionSignalsTitle": "Session signals in logs (per day)",
  "chartSessionSignalsBlurb": "Counts of JSONL lines matching --continue/--resume, retry/429 patterns, or interrupt/cancel (heuristic; not API truth).",
  "sigContinue": "continue",
  "sigResume": "resume",
  "sigRetry": "retry",
  "sigInterrupt": "interrupt",
  "cardHostParen": " (day)",
  "cardHostSub": "{out} out · {calls} calls · HitLim {hit}",
  "fcForensicDay": "Forensic (selected day)",
  "fcImpl": "Impl. cap @90%",
  "fcImplSub": "total/0.9 (illustrative, not Claude UI 90%/100%)",
  "fcBudget": "Budget reduction",
  "fcBudgetSub": "peak / (limitDay/0.9) — peak & limit auto-detected (token_forensics.js)",
  "forensicSummaryLine": "Forensic — {pick}: {fc} | Impl@90%: {impl} | Budget ~{bud}x | Peak {peak}",
  "chartDailyToken": "Daily token consumption",
  "chartCacheRatio": "Cache:output ratio (lower = more efficient)",
  "chartHostTitle": "Total tokens per day by host (stacked)",
  "chartHostBlurb": "Sum of input+output+cache read+cache creation per host. Bar height matches the full day (same idea as daily token chart).",
  "chartOutPerHour": "Output per active hour",
  "chartSubCachePct": "Subagent cache % of total cache",
  "chartTooltipSubCacheOfDay": "of day cache read",
  "chartTooltipSubCacheStackTotal": "Bar height ≈ day sub-cache share: {pct}%",
  "chartDS_cacheRead": "Cache read",
  "chartDS_output": "Output",
  "chartDS_cacheCreate": "Cache create",
  "chartLineCacheOut": "Cache:output",
  "chartTooltipCoDay": "C:O (day): {ratio}x",
  "chartTooltipOutCacheDay": "Output {out} · Cache read {cache}",
  "chartTooltipCoHostLine": "{host}: C:O {ratio}x",
  "chartOutPerHLabel": "Output/h",
  "hostStackFooter": "Sum (all hosts): ",
  "forensicDS_hitLimit": "Hit limit (JSONL lines)",
  "forensicDS_score": "Forensic score (3=? · 2=HIT · 1=<<P)",
  "forensicAxisHit": "Hit limit (red)",
  "forensicAxisCounts": "JSONL lines (signals + hits)",
  "forensicAxisForensic": "Forensic",
  "serviceAxisHours": "Hours",
  "serviceTooltipSessionSigHourNote": "Per hour: retry → red, interrupt → yellow (JSONL timestamp); continue/resume stay in clean work. Stacked bars count only hours with token usage.",
  "serviceTooltipSlideoutHint": "Extension releases, model change, outage report & forensic: click ▲ / ◇ or an entry in the Live panel → right slideout.",
  "tooltipVsPeak": "vs peak: ",
  "tooltipImpl90": "Impl@90%: ",
  "scanSourcesPrefix": "Scan sources: ",
  "statePathsTitle": "Local dashboard files (~/.claude):",
  "statePathDay": "Day cache: ",
  "statePathTodayIndex": "JSONL today index (mtime): ",
  "statePathReleases": "GitHub releases: ",
  "statePathMarketplace": "Marketplace versions: ",
  "statePathOutage": "Outage cache: ",
  "githubTokenLabel": "GitHub PAT (this browser tab only, sessionStorage):",
  "githubTokenSave": "Save",
  "githubTokenClear": "Clear",
  "githubTokenRefreshReleases": "Fetch releases",
  "githubTokenSavedLine": "GitHub PAT (saved) — value is not shown.",
  "githubTokenHint": "The token is sent only to this dashboard as the X-GitHub-Token header; the server calls the GitHub API (not your browser). A classic PAT is enough for public release metadata. Closing the tab clears it.",
  "githubTokenSaved": "Saved.",
  "githubTokenStoredPersistent": "PAT active (this tab only). No full JSONL rescan triggered.",
  "githubTokenCleared": "Cleared. The server falls back to GITHUB_TOKEN/GH_TOKEN if set.",
  "githubReleasesRefreshOk": "Release refresh started (background).",
  "githubReleasesRefreshFail": "Release refresh failed (network or admin token).",
  "marketplaceRefreshLabel": "VS Marketplace (extension versions)",
  "marketplaceRefreshOk": "Marketplace fetch started (background; check server log). SSE/timeline update when done.",
  "marketplaceRefreshFail": "Marketplace fetch failed (network, timeout, or 401 admin token).",
  "forensicChartTitle": "Forensic & hit limit per day",
  "forensicChartBlurbHtml": "One <strong>stacked bar</strong> per day: <strong>hit-limit</strong> JSONL line counts. <strong style=\"color:#f59e0b\">Line</strong> = forensic score (3=? · 2=HIT · 1=&lt;&lt;P). Below: <strong>session signals per day</strong> (stacked, <strong>outage hours</strong> as the <strong>top</strong> segment) + <strong>cache read</strong> as a line — see the next chart.",
  "forensicSignalsChartTitle": "Session signals & outage (stacked) + cache read",
  "forensicSignalsBlurbHtml": "Per <strong>day</strong>: <strong>bottom → top</strong> continue, resume, retry, interrupt, then <strong>outage (h)</strong> as the <strong>top</strong> bar segment (so it does not sit <em>under</em> a huge interrupt slice). Outage <strong>bar height is scaled</strong> (hours vs. JSONL counts); the <strong>tooltip</strong> shows real hours. <strong>Purple line</strong> = cache read (separate right scale) — same-day heuristic vs. interrupts/outage, not proof of cause. Tooltip adds output/cache and C:O.",
  "forensicSignalsAxisLines": "Signals + outage (h, bar scaled)",
  "forensicSignalsAxisOutage": "Outage (h)",
  "forensicSignalsAxisCacheRead": "Cache read (tokens)",
  "forensicDS_continueStack": "continue",
  "forensicDS_resumeStack": "resume",
  "forensicDS_retryStack": "retry",
  "forensicDS_interruptStack": "interrupt",
  "forensicDS_outageHoursDay": "Outage (h)",
  "forensicSignalsTooltipStackFooter": "Bars: signals/day, outage on top (tooltip = real h); purple line = cache read (own scale).",
  "unifiedAxisTokens": "Tokens",
  "unifiedChartTitle": "Token Budget & Outage Impact",
  "serviceChartTitle": "Service Impact: Work vs. Outage",
  "mainChartsSkelHint": "Placeholder — token charts render here as soon as usage data is ready (no need to wait for a full cache refresh).",
  "serviceBlurb": "<strong style=\"color:rgba(59,130,246,0.8)\">Blue</strong> = clean work. <strong style=\"color:rgba(239,68,68,0.8)\">Red</strong> = hours with API/server stress: declared outage <strong>or</strong> JSONL <code>retry</code> bucketed by the log entry’s clock hour (not a single lump for the whole day). <strong style=\"color:rgba(251,191,36,0.8)\">Yellow</strong> = client outage <strong>or</strong> JSONL <code>interrupt</code> in that hour. <strong style=\"color:rgba(107,114,128,0.6)\">Gray</strong> = outage without work in those hours. Continue/resume still count as clean hours. <strong>Stacked bars</strong> count only hours with real token usage (pure session signals alone do not add bar hours). Daily signal totals (stacked): <strong>Forensic</strong> section, chart below. <strong style=\"color:#8b5cf6\">Purple line</strong> = cache read (right scale). <strong style=\"color:#22d3ee\">◇</strong> / <strong style=\"color:#4ade80\">▲</strong> = model vs. extension day (click → <strong>slideout</strong>: release notes, outage report, forensic). <strong>Tooltip</strong> only bar/token summary; <strong>Live</strong> panel: outage list & compact extension list.",
  "serviceTooltipSessionSig": "JSONL lines (c / r / retry / interrupt)",
  "serviceDS_cleanWork": "Clean work",
  "serviceDS_affectedServer": "Work during API outage (retries)",
  "serviceDS_affectedClient": "Work during client bug (no token impact)",
  "serviceDS_affectedWork": "Work during outage",
  "serviceDS_outageOnly": "Outage (no work)",
  "thinkingNote": "⚠ Thinking tokens (internal reasoning) do not appear in the API response and are not counted here. They likely count against the session budget.",
  "tableCols": "Date|Output|Cache read|C:O|Overhead|Total|Calls|Hours|Hit limit|Sub%|Sub cache%|Out/h",
  "metaScanError": "Scan error: {msg}",
  "reportBtn": "Forensic Report",
  "reportTitle": "Forensic Report (Markdown)",
  "reportCopy": "Copy",
  "reportDownload": "Download .md",
  "reportCopied": "Copied!",
  "reportNoData": "No data — scan must complete first.",
  "outageChartTitle": "Outage Windows (status.claude.com)",
  "outageChartBlurbHtml": "Bars show outage time windows (UTC). <strong style=\"color:#f97316\">Orange</strong> = major, <strong style=\"color:#ef4444\">Red</strong> = critical, <strong style=\"color:#facc15\">Yellow</strong> = minor. Hover for details.",
  "outageDS_spans": "Outage window",
  "outageAxisHour": "Hour",
  "outageTotal": "total outage",
  "statusPending": "Status…",
  "statusPendingTip": "Loading Anthropic status…",
  "statusOutage": "Outage!",
  "statusOutageTip": "Active outage reported at Anthropic (status.claude.com)",
  "statusIncident": "Incident",
  "statusIncidentTip": "An incident was reported at Anthropic today (already resolved)",
  "statusOk": "OK",
  "statusOkTip": "No current incidents at Anthropic (status.claude.com)",
  "tooltipOutage": "Outage: ",
  "tooltipModelAdded": "Model added: ",
  "tooltipModelRemoved": "Model removed: ",
  "forensicDS_modelChange": "Model change",
  "forensicDS_outageHours": "Outage (h)",
  "serviceDS_versionChange": "Extension update",
  "tooltipVersionUpdate": "Extension: ",
  "serviceTooltipReleaseClock": "Marketplace/release time: ",
  "serviceTooltipReleaseUtc": "booked on UTC day (same as JSONL date): ",
  "serviceTooltipReleaseLocal": "local calendar day (this machine): ",
  "updateSlideoutClose": "Close",
  "updateDotAria": "Extension update: show details",
  "modelDotAria": "Model change: show details",
  "modelSlideoutHeading": "Model change",
  "modelSlideoutNoDetail": "No model-change details for this day.",
  "updateSlideoutHeading": "Extension update",
  "updateSlideoutNoDetail": "No version details for this day.",
  "updateSlideoutHighlights": "Release notes (excerpt)",
  "updateSlideoutHighlightsEmpty": "No excerpt yet: after each scan the server backfills missing releases via HTTPS into ~/.claude/claude-code-releases.json — wait for the live update, then open this panel again. Or open GitHub:",
  "updateSlideoutGithubReleases": "GitHub releases",
  "updateSlideoutStatusHeading": "Anthropic status / outages (this day)",
  "updateSlideoutOutageHoursLine": "Outage time: {total} h total (server {srv} h · client {cli} h)",
  "updateSlideoutOutageIncidents": "Incidents (status.claude.com)",
  "updateSlideoutOutageSpans": "Time windows (UTC, calendar day)",
  "updateSlideoutLikelyHit": "Note: many hit-limit lines in JSONL — possible overlap with outages (heuristic).",
  "updateSlideoutIncidentStart": "Started",
  "updateSlideoutIncidentResolved": "Resolved",
  "updateSlideoutIncidentOngoing": "ongoing / unknown",
  "updateSlideoutForensicHeading": "Forensic (summary)",
  "serviceTooltipReleaseGithubHint": "GitHub (release pages):",
  "timelineTitle": "Work & Outage Timeline (0–24h)",
  "timelineBlurbHtml": "<strong style=\"color:rgba(59,130,246,0.7)\">Blue</strong> = work window (first to last active hour, opacity = intensity). <strong style=\"color:rgba(239,68,68,0.7)\">Red</strong> = Anthropic outage. <strong style=\"color:#22d3ee\">◇</strong> = model change. Overlap = outage during work.",
  "timelineDS_work": "Work window",
  "timelineDS_outage": "Outage (status.claude.com)",
  "timelineAxisHour": "Time of day (UTC)",
  "userProfileSummary": "User Profile — {version} · {entrypoint} · {verCount} versions · Anomaly rate {rate}% ({anomalies}/{calls}) · Worst: {worst} ({worstCount})",
  "userProfileNoData": "User Profile — no data",
  "userVersionHealthTitle": "Version Health",
  "userVersionHealthBlurb": "Per-version anomaly breakdown (hit-limit, retry, interrupt, truncated, API error). Stacked bars — taller = more problems on that version.",
  "userEntrypointChartTitle": "Client Type (Timeline)",
  "userEntrypointBlurb": "How many calls each Claude Code version made, split by client type (VS Code, CLI, JetBrains). Shows which client drove usage on each version.",
  "userProfileCardVersion": "CLI Version",
  "userProfileCardEntrypoint": "Client",
  "userProfileCardAnomalyRate": "Anomaly Rate",
  "userProfileCardWorstVer": "Most Problematic",
  "userDSHitLimit": "Hit Limit (429)",
  "userDSRetry": "Retry",
  "userDSInterrupt": "Interrupt",
  "userDSTruncated": "Truncated",
  "userDSApiError": "API Error",
  "userSortAnomalies": "Most anomalies",
  "userSortNewest": "Newest version",
  "userSortCalls": "Most calls",
  "releaseStabilityTitle": "Release Stability",
  "releaseStabilityBlurb": "{total} versions ({matched} matched) \u00B7 {stable} stable \u00B7 {hotfixes} hotfixes \u00B7 {regressions} regression fixes",
  "releaseStabilityNoData": "Release Stability \u2014 no data",
  "releaseStabilityUnknown": "No release data",
  "releaseStabilityNoRelease": "Version not found in GitHub releases",
  "releaseStabilityStable": "Stable",
  "releaseStabilityRegression": "Regression Fix",
  "releaseStabilityHotfix": "Same-Day Hotfix",
  "releaseStabilitySkipped": "Skipped patches",
  "releaseStabilityXAxis": "Days active",
  "budgetSummary": "Budget Efficiency \u2014 Overhead {overhead}x \u00B7 Output {outputPct}% \u00B7 Cache Miss {cmr}% \u00B7 {retries} retries \u00B7 {interrupts} interrupts",
  "budgetNoData": "Budget Efficiency \u2014 no data",
  "budgetCardOutput": "Effective Output",
  "budgetCardOutputSub": "Output / total tokens",
  "budgetCardOverhead": "Overhead Factor",
  "budgetCardOverheadSub": "Total / output tokens",
  "budgetCardCacheMiss": "Cache Miss Rate",
  "budgetCardCacheMissSub": "Creation / (creation + read)",
  "budgetCardLost": "Lost Signals",
  "budgetCardLostSub": "{r} retries \u00B7 {i} interrupts \u00B7 {e} API errors",
  "budgetWaterfallTitle": "Token Budget Breakdown",
  "budgetWaterfallBlurb": "Where your token budget goes \u2014 stacked from output (productive) through cache, input, to creation overhead.",
  "budgetWfOutput": "Output",
  "budgetWfCacheRead": "Cache Read",
  "budgetWfInput": "Input",
  "budgetWfCacheCreate": "Cache Creation",
  "budgetWfBudget": "Token Budget",
  "budgetWfProductive": "Productive",
  "budgetWfOverhead": "Overhead",
  "budgetWfYou": "You",
  "budgetWfResult": "Total Usage",
  "budgetFlowBudget": "Budget Flow",
  "budgetFlowApi": "API Flow",
  "budgetFlowUser": "User Flow",
  "budgetWfXAxis": "Tokens",
  "budgetWfXCost": "Weighted cost (relative)",
  "budgetWfVolume": "Volume",
  "budgetWfCost": "Quota Cost",
  "budgetWfOfQuota": "of estimated quota",
  "budgetWaterfallBlurbCost": "Estimated quota cost breakdown \u2014 weighted by token type pricing (output=1x, input=0.33x, cache read=0.03x, creation=0.42x).",
  "budgetTrendTitle": "Efficiency Trend",
  "budgetTrendBlurb": "Output % grows up (good), overhead grows down (bad). Cache miss % as dashed line.",
  "budgetQuotaTitle": "Quota Usage",
  "budgetQuotaBlurb": "5h/7d quota utilization and fallback budget percentage from API headers.",
  "budgetTrendOverhead": "Overhead (x)",
  "budgetTrendOutputPct": "Output %",
  "budgetTrendCacheMiss": "Cache Miss %",
  "budgetTrendYOverhead": "Overhead factor",
  "budgetTrendYPct": "Percentage",
  "budgetTrendQuota5h": "Quota 5h %",
  "budgetTrendQuota7d": "Quota 7d %",
  "budgetTrendYQuota": "Quota / Output %",
  "budgetTrendFallback": "Fallback Budget %",
  "budgetAlertTitle": "CAPACITY REDUCED",
  "budgetAlertFallback": "Effective budget is {pct}% of maximum (fallback-percentage: {pct}%)",
  "budgetAlertOverage": "Hard cutoff \u2014 no buffer (overage: rejected)",
  "budgetAlertClaim": "Binding limit: {claim}",
  "budgetCardFallback": "Effective Budget",
  "budgetCardFallbackSub": "fallback-percentage from API headers",
  "budgetCardOverage": "Overage Policy",
  "budgetCardClaim": "Binding Window",
  "budgetCardClaimSub": "representative-claim",
  "budgetCardForecast": "5h Remaining",
  "budgetCardForecastSub": "Estimated hours left at current rate",
  "budgetCardOutage": "Outage Loss",
  "budgetCardOutageSub": "Hours lost to service outages",
  "budgetCardTruncated": "Tool Bloat",
  "budgetCardTruncatedSub": "Truncated tool results (>50K tokens lost)",
  "proxySummaryLine": "Proxy — {reqs} requests · {errs} errors · Quota 5h: {q5h}% · 7d: {q7d}%",
  "proxySummaryNoData": "Proxy Analytics — no proxy data",
  "proxyNote": "Data from transparent Anthropic proxy (NDJSON logs). Rate-limit headers, cache health, latency and token attribution per API call.",
  "proxyRatelimitTitle": "Rate Limit (Quota Utilization)",
  "proxyRatelimitBlurb": "Doughnut = current quota utilization. 5-hour window is always the bottleneck. Yellow >50%, red >80%.",
  "proxyGauge5hTitle": "5h Window",
  "proxyGauge7dTitle": "7d Window",
  "proxyGaugeRemaining": "remaining",
  "proxyGaugeUsed": "used",
  "proxyGaugeResetIn": "Reset in {h}h {m}m",
  "proxyTokenChartTitle": "Token Cost Attribution (per day)",
  "proxyTokenBlurb": "Stacked bars: cache read, cache creation, output tokens. The gap between visible tokens and quota cost = invisible thinking tokens.",
  "proxyLatencyChartTitle": "API Latency (per day)",
  "proxyLatencyBlurb": "Average, min and max response time in ms. Spikes indicate peak-hour tightening or server load.",
  "proxyCardRequests": "Proxy Requests",
  "proxyCardRequestsSub": "{errs} errors ({rate}%)",
  "proxyCardLatency": "Avg Latency",
  "proxyCardLatencySub": "min {min}ms · max {max}ms",
  "proxyCardCacheRatio": "Cache Read Ratio",
  "proxyCardCacheRatioSub": "{healthy} healthy · {affected} affected",
  "proxyCardModels": "Model Split",
  "proxyCardModelsSub": "{opus} Opus · {sonnet} Sonnet · {other} other",
  "proxyCardQuota5h": "5h Quota",
  "proxyCardQuota7d": "7d Quota",
  "proxyDSCacheRead": "Cache read",
  "proxyDSCacheCreate": "Cache create",
  "proxyDSOutput": "Output",
  "proxyDSAvgLatency": "Avg latency (ms)",
  "proxyDSMinLatency": "Min",
  "proxyDSMaxLatency": "Max",
  "proxyHourlyTitle": "Requests per Hour (today)",
  "proxyHourlyBlurb": "Requests per hour aggregated across all proxy days. Intensity shows relative load. Reveals your typical usage pattern over time.",
  "proxyModelTitle": "Model & Status Breakdown",
  "proxyModelBlurb": "Stacked bars: requests per model per day. Yellow line: average latency. Shows model distribution and performance over time.",
  "proxyInvisibleCostNote": "Invisible cost: {visible} visible tokens, {cache} cache tokens used {perPct} visible tokens per 1% quota — thinking tokens are not counted here.",
  "proxyDSRequestsPerHour": "Requests",
  "proxyDSModelRequests": "Requests",
  "proxyDSModelLatency": "Avg latency",
  "proxyColdStartInfo": "{cold} cold starts of {total} requests (avg cache ratio: {avg}%, min: {min}%)",
  "proxyJsonlNoData": "No JSONL data — sync local logs via POST /api/claude-data-sync to compare.",
  "proxyJsonlNoOverlap": "No overlapping days between JSONL and proxy logs.",
  "proxyJsonlCompare": "{days} days compared: JSONL {jsonl} vs Proxy {proxy} tokens (ratio {ratio}x). >1.5x suggests JSONL duplication.",
  "proxyHourlyLatencyTitle": "Latency per Hour (avg + max)",
  "proxyHourlyLatencyBlurb": "Blue = average response time, red = peak latency per hour. Aggregated across all proxy days. Spikes indicate peak-hour rate throttling.",
  "proxyErrorTrendTitle": "Error / 429 Rate Trend",
  "proxyErrorTrendBlurb": "Error rate and false-429 rate per day. Rising trends indicate tightening rate limits or degraded service.",
  "proxyDSErrorRate": "Error Rate",
  "proxyDSFalse429Rate": "False 429 Rate",
  "proxyCacheTrendTitle": "Cache Quality Trend",
  "proxyCacheTrendBlurb": "Cache read ratio (green line) and cold starts (blue bars) per day. Drops in ratio or spikes in cold starts signal cache degradation.",
  "proxyDSCacheRatio": "Cache Read Ratio",
  "proxyDSColdStarts": "Cold Starts",
  "proxyEfficiencyTrendTitle": "Efficiency Trend",
  "proxyEfficiencyTrendBlurb": "Heatmap at top: overview across all metrics and days, color-normalized per row (blue = lowest value in that metric, red = highest). Small multiples below: JSONL/Proxy Ratio with B8 baseline at 2.87x (thinking inflation), Visible Tokens per 1% of 5h quota (proxy-captured, coverage shown in tooltip), Cache Miss % (cold context vs. reuse). Hover any cell for raw + normalized values.",
  "proxyDSJsonlRatio": "JSONL/Proxy Ratio",
  "proxyDSVisPerPct": "Visible Tokens/1%",
  "proxyDSCoverage": "Coverage %",
  "healthScoreTitle": "Health Score",
  "healthScoreSummary": "{score}/10 — {warns} warnings, {crits} critical",
  "healthScoreNoData": "Health Score — waiting for data",
  "healthQuota5h": "Quota 5h",
  "healthThinkingGap": "Thinking Gap",
  "healthCacheHealth": "Cache Health",
  "healthErrorRate": "Error Rate",
  "healthHitLimits": "Hit Limits/d",
  "healthLatency": "Avg Latency",
  "healthInterrupts": "Interrupts/d",
  "healthColdStarts": "Cold Starts",
  "healthRetries": "Retries/d",
  "healthFalse429": "False 429 (B3)",
  "healthTruncations": "Truncations (B5)",
  "healthContextResets": "Context Resets (B4)",
  "healthQuotaBench": "Tokens/1% Quota",
  "healthAnomalStops": "Anomal Stops",
  "findingsTitle": "Key Findings",
  "findingsSummary": "{total} findings — {reds} critical, {yellows} warnings",
  "findingsNoData": "Key Findings — waiting for data",
  "findingThinkingGap": "Thinking Token Gap",
  "findingThinkingGapDetail": "JSONL reports {jsonl}, Proxy sees {proxy}. PRELIM duplication inflates JSONL counts.",
  "findingOverhead": "Token Overhead",
  "findingOverheadDetail": "{total} total vs {output} output across {days} days. Cache dominates.",
  "findingHitLimits": "Hit Limits",
  "findingHitLimitsDetail": "{total} rate-limit hits in {days} days ({perDay}/day avg).",
  "findingInterrupts": "Interrupts",
  "findingInterruptsDetail": "{interrupts} interrupts vs {hits} hit-limits (ratio {ratio}x). Sessions constantly disrupted.",
  "findingQuota": "Quota 5h / 7d",
  "findingQuotaDetail": "5h: {q5}%, 7d: {q7}% used. {reqs} requests, only {output} visible output.",
  "findingPeakDay": "Peak Day",
  "findingPeakDayDetail": "{total} tokens, {calls} calls, {overhead}x overhead.",
  "findingRetries": "API Retries",
  "findingRetriesDetail": "{total} retries ({perDay}/day). API errors force repeated calls.",
  "findingCacheParadox": "Cache Paradox",
  "findingCacheParadoxDetail": "High cache ratio masks context degradation. Cache hits stay high even after silent compaction.",
  "findingFallback": "Effective Budget",
  "findingFallbackDetail": "Anthropic fallback-percentage is {pct}%. Your effective token budget is {pct}% of the theoretical maximum. Below 100% means a silent capacity reduction.",
  "findingOveragePolicy": "Overage Policy",
  "findingOveragePolicyDetail": "Overage status: {status} (reason: {reason}). 'rejected' means hard cutoff — no buffer zone when you hit the limit.",
  "findingClaim": "Binding Constraint",
  "findingClaimDetail": "The rate-limit window that is currently binding your usage. 'five_hour' means the 5h session window is the active limit.",
  "healthCollapseSummary": "Health {score}/10 — {warns} warnings, {crits} critical · {findings} findings",
  "filterBarTitle": "Filter criteria",
  "filterDateRange": "Date range:",
  "filterScope": "Charts:",
  "filterHost": "Source:",
  "filterHostAll": "All",
  "healthHistoryLabel": "Health Score",
  "healthHistoryWarn": "Warning",
  "healthHistoryCrit": "Critical",
  "incidentHistoryLabel": "Incidents & Hit Limits (per day)",
  "incidentDSOutageHours": "Outage (hours)",
  "incidentDSHitLimits": "Hit limits",
  "incidentAxisOutage": "Outage (h)",
  "incidentAxisHitLimits": "Hit limits",
  "outageTimelineTitle": "Service Quality (24h per day)",
  "outageTimelineOk": "none",
  "availKpiSummary": "Key Metrics",
  "availKpiTotal": "Overall Availability",
  "availKpiPeriod": "Period",
  "availKpiDowntime": "Downtime",
  "availKpiMonth": "Month",
  "availKpiIncidents": "Incidents",
  "availKpiHours": "Hours",
  "availKpiAvail": "Availability",
  "availKpiImpact": "By Severity",
  "availKpiKind": "By Source",
  "uptimeChartTitle": "Service Uptime (24h per day)",
  "uptimeOperational": "Operational",
  "uptimeDegraded": "Degraded",
  "uptimePartial": "Partial Outage",
  "uptimeOutage": "Outage",
  "availKpiTrend": "vs. prev. month",
  "availKpiCurrent": "(current)",

  "econSummaryLine": "Economic Usage \u2014 {sessions} sessions, efficiency {ratio}%",
  "econSummaryNoData": "Economic Usage \u2014 no session data",
  "econDateLabel": "Date:",
  "econSessionLabel": "Session:",
  "econSessionInfo": "{turns} turns \u00b7 Output {output} \u00b7 Cache Read {cacheRead} \u00b7 Total {total}",
  "econWasteTitle": "Cumulative Usage Curve",
  "econWasteBlurb": "Cumulative token consumption per turn. The gap between Cache Read (gray) and Output (green) reveals when a session becomes inefficient.",
  "econWasteOutput": "Output (cumulative)",
  "econWasteCacheRead": "Cache Read (cumulative)",
  "econWasteCacheCreate": "Cache Creation (cumulative)",
  "econWasteInput": "Input (cumulative)",
  "econWasteSplitHint": "Consider splitting session here",
  "econWasteMonthTitle": "Cumulative Usage Curve \u2014 Monthly",
  "econWasteMonthBlurb": "Cumulative token consumption per day across the month. Shows overall accumulation of Cache Read vs. Output over all days.",
  "econEfficiencyTitle": "Efficiency Timeline",
  "econEfficiencyBlurb": "Output tokens vs. total tokens per hour. The orange band marks Anthropic Peak Hours (1\u20137 PM GMT) with increased quota consumption.",
  "econEfficiencyOutput": "Output Tokens",
  "econEfficiencyTotal": "Total Tokens",
  "econEfficiencyRatio": "Efficiency Ratio",
  "econEfficiencyPeakBand": "Peak Hours",
  "econDayCompareTitle": "Daily Comparison \u2014 Efficiency Ratio",
  "econDayCompareBlurb": "Output / Total per day \u2014 higher = more productive yield per token consumed."
}
