{
  "pageTitle": "Claude Code Usage Dashboard",
  "heading": "Claude Code Token Usage",
  "subModelsHtml": "Only <strong>Claude</strong> models (<code>claude-*</code>) — no <code>&lt;synthetic&gt;</code> lines.",
  "langLabel": "Language",
  "ariaLangGroup": "Choose language",
  "liveFilesAria": "Scanned JSONL files",
  "liveFilesHint": "Each line: source · path (~ = home on this machine). Hover or focus (Tab) keeps the list open.",
  "liveFilesHead0": "Scanned JSONL",
  "liveFilesHeadN": "Scanned JSONL ({n})",
  "scanStill": "Scan still running…",
  "noJsonlList": "No .jsonl under configured scan roots (see data source / CLAUDE_USAGE_EXTRA_BASES).",
  "sseDisconnected": "Disconnected — retrying…",
  "liveTriggerScanning": "Live — scan running",
  "liveTriggerZero": "0 JSONL files",
  "liveTriggerMany": "{n} JSONL — hover or Tab for list; tap toggles on touch",
  "metaScanning": "Scanning ~/.claude/projects in the background… Updates via SSE. Files read in small batches.",
  "metaForensicScanning": "Forensic — scan running…",
  "metaForensicNoteFirst": "First run after server start; then every {sec}s in the background.",
  "liveWaitData": "Live — waiting for data…",
  "metaNoFiles": "No data: 0 .jsonl files in scan roots (~/.claude/projects and CLAUDE_USAGE_EXTRA_BASES if set). Without matching logs, cards and tables stay empty.",
  "metaNoUsage": "No daily values: read {files} file(s) but no usage lines with model claude-*.",
  "forensicSummaryNoData": "Forensic (token_forensics) — no data",
  "metaParsed": "Parsed {files} log files | Last update: {time} | Auto-refresh every {sec}s",
  "metaParsedInProgress": "Loading {done}/{total} log files | Last update: {time} | Auto-refresh every {sec}s",
  "metaChartsHint": "| Cards: selected day (dropdown); charts: all days.",
  "metaDetailsSummaryLine": "{files} log files · every {sec}s — expand for notes & status",
  "metaSummaryScanning": "Scanning… — expand",
  "metaDetailsScanProgress": "{done}/{total} log files · every {sec}s — loading live",
  "metaScanningExpanded": "Scan: read {done}/{total} log files (refresh every {sec}s). Charts appear once data exists — not final yet.",
  "metaSummaryNoFiles": "No .jsonl under scan roots — expand",
  "metaSummaryNoUsage": "No usage in {files} file(s) — expand",
  "calTodaySuffix": " — calendar today",
  "zeroLogsSuffix": " (0 in logs)",
  "dayPickerHintZero": "Calendar today: 0 tokens in logs — pick another day with usage.",
  "limitSourceTooltip": "Anthropic / Claude Code enforce session and rate limits; JSONL mostly shows successful API usage. Hit limit counts lines matching typical limit/error patterns.",
  "dailyDetailPrefix": "Daily detail — ",
  "dailyDetailClearHost": "All hosts",
  "dailyDetailHostRowTitle": "Click: this host only in daily detail",
  "dailyDetailFilteredRowTitle": "Click: show all hosts again",
  "liveConnected": "Live ({time})",
  "dayPickerLabel": "Cards & table (pick day)",
  "dayPickerAria": "Day for cards and daily detail",
  "cardDayOutput": "Day output",
  "cardDayCacheRead": "Day cache read",
  "cardCacheOutSub": "Cache:Out {ratio}x",
  "cardDayTotal": "Day total",
  "cardCallsActiveSub": "{calls} calls, {hours}h active",
  "cardHitDay": "Hit limit (day)",
  "cardHitDaySub": "JSONL lines suggesting limits/429 that day",
  "cardHitAll": "Hit limit (all days)",
  "cardHitAllSub": "Sum across all days",
  "cardOverhead": "Day overhead",
  "cardOverheadSub": "tokens per output token",
  "cardPeak": "Peak day total",
  "cardPeakSub": "{date} (highest Claude usage in logs)",
  "cardAllOut": "All-time output",
  "cardAllOutSub": "{days} days with usage",
  "cardAllCache": "All-time cache read",
  "cardAllCacheSub": "{pct} of total",
  "cardHostParen": " (day)",
  "cardHostSub": "{out} out · {calls} calls · HitLim {hit}",
  "fcForensicDay": "Forensic (selected day)",
  "fcImpl": "Impl. cap @90%",
  "fcImplSub": "total/0.9 (illustrative, not Claude UI 90%/100%)",
  "fcBudget": "Budget reduction",
  "fcBudgetSub": "peak / (today/0.9) as in token_forensics.js",
  "forensicSummaryLine": "Forensic — {pick}: {fc} | Impl@90%: {impl} | Budget ~{bud}x | Peak {peak}",
  "chartDailyToken": "Daily token consumption",
  "chartCacheRatio": "Cache:output ratio (lower = more efficient)",
  "chartHostTitle": "Total tokens per day by host (stacked)",
  "chartHostBlurb": "Sum of input+output+cache read+cache creation per host. Bar height matches the full day (same idea as daily token chart).",
  "chartOutPerHour": "Output per active hour",
  "chartSubCachePct": "Subagent cache % of total cache",
  "chartTooltipSubCacheOfDay": "of day cache read",
  "chartTooltipSubCacheStackTotal": "Bar height ≈ day sub-cache share: {pct}%",
  "chartDS_cacheRead": "Cache read",
  "chartDS_output": "Output",
  "chartDS_cacheCreate": "Cache create",
  "chartLineCacheOut": "Cache:output",
  "chartTooltipCoDay": "C:O (day): {ratio}x",
  "chartTooltipOutCacheDay": "Output {out} · Cache read {cache}",
  "chartTooltipCoHostLine": "{host}: C:O {ratio}x",
  "chartOutPerHLabel": "Output/h",
  "hostStackFooter": "Sum (all hosts): ",
  "forensicDS_hitLimit": "Hit limit (JSONL lines)",
  "forensicDS_score": "Forensic score (3=? · 2=HIT · 1=<<P)",
  "forensicAxisHit": "Hit limit (red)",
  "forensicAxisForensic": "Forensic",
  "tooltipVsPeak": "vs peak: ",
  "tooltipImpl90": "Impl@90%: ",
  "scanSourcesPrefix": "Scan sources: ",
  "forensicChartTitle": "Forensic & hit limit per day",
  "forensicChartBlurbHtml": "<strong style=\"color:#ef4444\">Red (bars)</strong> = hit-limit-like JSONL line count. <strong style=\"color:#f59e0b\">Line</strong> = score 3=? · 2=HIT · 1=&lt;&lt;P (peak comparison, not Claude UI 90%/100%).",
  "tableCols": "Date|Output|Cache read|C:O|Overhead|Total|Calls|Hours|Hit limit|Sub%|Sub cache%|Out/h",
  "metaScanError": "Scan error: {msg}"
}
