{
  "pageTitle": "Claude Code Nutzungs-Dashboard",
  "heading": "Claude Code Token-Nutzung",
  "subModelsHtml": "Nur <strong>Claude</strong>-Modelle (<code>claude-*</code>) — keine <code>&lt;synthetic&gt;</code>-Zeilen.",
  "langLabel": "Sprache",
  "ariaLangGroup": "Sprache wählen",
  "liveFilesAria": "Gescannte JSONL-Dateien",
  "liveFilesHint": "Pro Zeile: Quelle · Pfad (~ = User-Home dieses Rechners). Hover oder Fokus (Tab) hält die Liste offen.",
  "liveFilesHead0": "Gescannte JSONL",
  "liveFilesHeadN": "Gescannte JSONL ({n})",
  "scanStill": "Scan läuft noch…",
  "noJsonlList": "Keine .jsonl in den konfigurierten Scan-Wurzeln (siehe Datenquelle / CLAUDE_USAGE_EXTRA_BASES).",
  "sseDisconnected": "Getrennt — verbinde erneut…",
  "liveTriggerScanning": "Live — Scan läuft",
  "liveTriggerZero": "0 JSONL-Dateien",
  "liveTriggerMany": "{n} JSONL — Hover oder Tab für Liste; Klick hält auf Touch offen",
  "metaScanning": "Scanne ~/.claude/projects im Hintergrund… Inhalt folgt per Live-Update (SSE). Dateien werden in kleinen Batches gelesen.",
  "metaForensicScanning": "Forensic — Scan läuft…",
  "metaForensicNoteFirst": "Erster Lauf nach Serverstart; danach alle {sec}s im Hintergrund.",
  "liveWaitData": "Live — warte auf Daten…",
  "metaNoFiles": "Keine Daten: 0 .jsonl-Dateien in den Scan-Wurzeln (~/.claude/projects ggf. + CLAUDE_USAGE_EXTRA_BASES). Ohne passende Logs bleiben Karten und Tabellen leer.",
  "metaNoUsage": "Keine Tageswerte: {files} Datei(en) gelesen, aber keine usage-Zeilen mit Modell claude-*.",
  "forensicSummaryNoData": "Forensic (token_forensics) — keine Daten",
  "metaParsed": "Parsed {files} Log-Dateien | Stand: {time} | Auto-Refresh alle {sec}s",
  "metaParsedInProgress": "Einlesen {done}/{total} Log-Dateien | Stand: {time} | Auto-Refresh alle {sec}s",
  "metaChartsHint": "| Karten: gewählter Tag (Dropdown), Diagramme: alle Tage.",
  "metaDetailsSummaryLine": "{files} Log-Dateien · alle {sec}s — aufklappen für Hinweise & Datenstand",
  "metaSummaryScanning": "Scan läuft… — aufklappen",
  "metaDetailsScanProgress": "{done}/{total} Log-Dateien · alle {sec}s — Daten laufen ein (live)",
  "metaScanningExpanded": "Scan: {done}/{total} Log-Dateien gelesen (alle {sec}s Refresh). Diagramme erscheinen mit ersten Treffern — noch nicht final.",
  "metaSummaryNoFiles": "Keine .jsonl in den Scan-Wurzeln — aufklappen",
  "metaSummaryNoUsage": "Keine Nutzung in {files} Datei(en) — aufklappen",
  "calTodaySuffix": " — Kalender heute",
  "zeroLogsSuffix": " (0 in Logs)",
  "dayPickerHintZero": "Kalender-heute: 0 Tokens in den Logs — älteren Tag mit Nutzung wählen.",
  "limitSourceTooltip": "Session- und Rate-Limits setzt Anthropic/Claude Code; JSONL enthält meist nur erfolgreiche API-Nutzung (usage). Hit Limit zählt Zeilen mit typischen Limit-/Fehlertexten.",
  "dailyDetailPrefix": "Tagesdetail — ",
  "dailyDetailClearHost": "Alle Hosts",
  "dailyDetailHostRowTitle": "Klick: nur dieser Host im Tagesdetail",
  "dailyDetailFilteredRowTitle": "Klick: wieder alle Hosts",
  "liveConnected": "Live ({time})",
  "dayPickerLabel": "Karten & Tabelle (Tag wählen)",
  "dayPickerAria": "Tag für Karten und Tagesdetail",
  "cardDayOutput": "Tag Output",
  "cardDayCacheRead": "Tag Cache Read",
  "cardCacheOutSub": "Cache:Out {ratio}x",
  "cardDayTotal": "Tag Total",
  "cardCallsActiveSub": "{calls} Aufrufe, {hours}h aktiv",
  "cardHitDay": "Hit Limit (Tag)",
  "cardHitDaySub": "JSONL-Zeilen Limit/429 an diesem Tag",
  "cardHitAll": "Hit Limit (alle Tage)",
  "cardHitAllSub": "Summe über alle Tage",
  "cardOverhead": "Tag Overhead",
  "cardOverheadSub": "Tokens pro Output-Token",
  "cardPeak": "Peak-Tag Total",
  "cardPeakSub": "{date} (höchste Claude-Nutzung im Log)",
  "cardAllOut": "Gesamt Output",
  "cardAllOutSub": "{days} Tage mit Nutzung",
  "cardAllCache": "Gesamt Cache Read",
  "cardAllCacheSub": "{pct} vom Total",
  "cardHostParen": " (Tag)",
  "cardHostSub": "{out} out · {calls} calls · HitLim {hit}",
  "fcForensicDay": "Forensic (gew. Tag)",
  "fcImpl": "Impl. cap @90%",
  "fcImplSub": "total/0.9 (Rechenbeispiel, nicht UI-90%/100%)",
  "fcBudget": "Budget-Reduktion",
  "fcBudgetSub": "peak / (heute/0.9) wie Fazit token_forensics.js",
  "forensicSummaryLine": "Forensic — {pick}: {fc} | Impl@90%: {impl} | Budget ~{bud}× | Peak {peak}",
  "chartDailyToken": "Täglicher Token-Verbrauch",
  "chartCacheRatio": "Cache:Output-Verhältnis (niedriger = effizienter)",
  "chartHostTitle": "Total-Tokens pro Tag nach Host (gestapelt)",
  "chartHostBlurb": "Summe Input+Output+Cache Read+Cache Create je Host. Balkenhöhe entspricht dem Gesamttag (wie „Täglicher Token-Verbrauch“).",
  "chartOutPerHour": "Output pro aktiver Stunde",
  "chartSubCachePct": "Subagent-Cache % vom Gesamt-Cache",
  "chartTooltipSubCacheOfDay": "vom Tages-Cache-Read",
  "chartTooltipSubCacheStackTotal": "Balkenhöhe ≈ Sub-Cache-Anteil Tag: {pct}%",
  "chartDS_cacheRead": "Cache Read",
  "chartDS_output": "Output",
  "chartDS_cacheCreate": "Cache Create",
  "chartLineCacheOut": "Cache:Output",
  "chartTooltipCoDay": "C:O (Tag): {ratio}x",
  "chartTooltipOutCacheDay": "Output {out} · Cache Read {cache}",
  "chartTooltipCoHostLine": "{host}: C:O {ratio}x",
  "chartOutPerHLabel": "Output/h",
  "hostStackFooter": "Summe (alle Hosts): ",
  "forensicDS_hitLimit": "Hit Limit (JSONL-Zeilen)",
  "forensicDS_score": "Forensic-Score (3=? · 2=HIT · 1=<<P)",
  "forensicAxisHit": "Hit Limit (rot)",
  "forensicAxisForensic": "Forensic",
  "tooltipVsPeak": "vs Peak: ",
  "tooltipImpl90": "Impl@90%: ",
  "scanSourcesPrefix": "Scan-Quellen: ",
  "forensicChartTitle": "Forensic & Hit Limit pro Tag",
  "forensicChartBlurbHtml": "<strong style=\"color:#ef4444\">Rot (Balken)</strong> = Zähler Hit-Limit-Zeilen in JSONL. <strong style=\"color:#f59e0b\">Linie</strong> = Score 3=? · 2=HIT · 1=&lt;&lt;P (Peak-Vergleich, nicht Claude-UI 90%/100%).",
  "tableCols": "Datum|Output|Cache Read|V:O|Overhead|Total|Aufrufe|Std.|Hit Limit|Sub%|Sub-Cache%|Out/h",
  "metaScanError": "Scan-Fehler: {msg}"
}
