{
  "pageTitle": "Claude Code Nutzungs-Dashboard",
  "heading": "Claude Code Token-Nutzung",
  "subModelsHtml": "Nur <strong>Claude</strong>-Modelle (<code>claude-*</code>) — keine <code>&lt;synthetic&gt;</code>-Zeilen.",
  "langLabel": "Sprache",
  "ariaLangGroup": "Sprache wählen",
  "liveFilesAria": "Gescannte JSONL-Dateien",
  "livePanelAria": "Live-Panel: gescannte JSONL, Anthropic-Outages, Extension-Updates",
  "liveFilesHint": "Panel per Klick auf \u201eLive\u201c \u00f6ffnen/schlie\u00dfen. Pro Zeile: Quelle \u00b7 Pfad (~ = User-Home dieses Rechners).",
  "liveFilesHead0": "Gescannte JSONL",
  "liveFilesHeadN": "Gescannte JSONL ({n})",
  "scanStill": "Scan läuft noch…",
  "noJsonlList": "Keine .jsonl in den konfigurierten Scan-Wurzeln (siehe Datenquelle / CLAUDE_USAGE_EXTRA_BASES).",
  "sseDisconnected": "Getrennt — verbinde erneut…",
  "liveTriggerScanning": "Live — Scan läuft",
  "liveTriggerZero": "0 JSONL-Dateien",
  "liveTriggerMany": "{n} JSONL — Klick \u00f6ffnet das Live-Panel",
  "liveOutageHead": "Outages (status.claude.com)",
  "liveOutageEmpty": "Keine Outage-Eintr\u00e4ge im aktuellen Zeitraum.",
  "liveExtHead": "Extension-Updates (Claude Code)",
  "liveExtEmpty": "Keine erkannten Extension-Wechsel im Zeitraum.",
  "liveExtOpenAria": "Details zum Extension-Update",
  "metaShellReady": "Layout steht — die Seitenstruktur ist schon da. Ein Live-Scan streamt Log-Daten; Diagramme f\u00fcllen sich sobald Tage erkannt werden (kein Warten auf einen fertigen Day-Cache auf der Platte).",
  "metaDetailsSummaryDefault": "Meta & Datenquellen",
  "dayPickerScanning": "Scan l\u00e4uft\u2026",
  "dayPickerNoData": "Noch kein Tag w\u00e4hlbar",
  "metaScanning": "Scanne ~/.claude/projects im Hintergrund… Inhalt folgt per Live-Update (SSE). Dateien werden in kleinen Batches gelesen.",
  "metaForensicScanning": "Forensic — Scan läuft…",
  "metaForensicNoteFirst": "Erster Lauf nach Serverstart; danach alle {sec}s im Hintergrund.",
  "liveWaitData": "Live — warte auf Daten…",
  "metaNoFiles": "Keine Daten: 0 .jsonl-Dateien in den Scan-Wurzeln (~/.claude/projects ggf. + CLAUDE_USAGE_EXTRA_BASES). Ohne passende Logs bleiben Karten und Tabellen leer.",
  "metaNoUsage": "Keine Tageswerte: {files} Datei(en) gelesen, aber keine usage-Zeilen mit Modell claude-*.",
  "forensicSummaryNoData": "Forensic (token_forensics) — keine Daten",
  "metaParsed": "Parsed {files} Log-Dateien | Stand: {time} | Auto-Refresh alle {sec}s",
  "metaParsedInProgress": "Einlesen {done}/{total} Log-Dateien | Stand: {time} | Auto-Refresh alle {sec}s",
  "metaChartsHint": "| Karten & Tabelle: gewählter Tag. Hauptdiagramme: Umschalter \u00bbAlle Tage / 24 h\u00ab.",
  "metaChartsHintHourly": "24h-Modus: ein Kalendertag in Stunden; Token-Balken anteilig nach API-Events/Stunde (geschätzt).",
  "mainChartsScopeLabel": "Hauptdiagramme:",
  "mainChartsScopeAria": "Diagramme: Zeitraum aller Tage oder Stunden des gewählten Tags",
  "mainChartsScopeTimeline": "Alle Tage",
  "mainChartsScopeHourly": "24 h (gew. Tag)",
  "chartDailyTokenHourly": "Token je Stunde (gesch\u00e4tzt)",
  "chartCacheRatioHourly": "Cache:Output je Stunde (gesch\u00e4tzt)",
  "chartOutPerHourHourly": "API-Events je Stunde",
  "chartSubCachePctHourly": "Session-Signale je Stunde",
  "chartTooltipHourlyTokenEst": "Token-Zeilen: Tageswert \u00d7 (Events dieser Stunde / Summe Events Tag).",
  "chartHourlyApiEventsLabel": "API-Events",
  "metaDetailsSummaryLine": "{files} Log-Dateien · alle {sec}s — aufklappen für Hinweise & Datenstand",
  "metaSummaryScanning": "Scan läuft… — aufklappen",
  "metaDetailsScanProgress": "{done}/{total} Log-Dateien · alle {sec}s — Daten laufen ein (live)",
  "metaScanningExpanded": "Scan: {done}/{total} Log-Dateien gelesen (alle {sec}s Refresh). Diagramme erscheinen mit ersten Treffern — noch nicht final.",
  "metaSummaryNoFiles": "Keine .jsonl in den Scan-Wurzeln — aufklappen",
  "metaSummaryNoUsage": "Keine Nutzung in {files} Datei(en) — aufklappen",
  "calTodaySuffix": " — Kalender heute",
  "zeroLogsSuffix": " (0 in Logs)",
  "dayPickerHintZero": "Kalender-heute: 0 Tokens in den Logs — älteren Tag mit Nutzung wählen.",
  "limitSourceTooltip": "Session- und Rate-Limits setzt Anthropic/Claude Code; JSONL enthält meist nur erfolgreiche API-Nutzung (usage). Hit Limit zählt Zeilen mit typischen Limit-/Fehlertexten.",
  "dailyDetailPrefix": "Tagesdetail — ",
  "dailyDetailClearHost": "Alle Hosts",
  "dailyDetailHostRowTitle": "Klick: nur dieser Host im Tagesdetail",
  "dailyDetailFilteredRowTitle": "Klick: wieder alle Hosts",
  "forensicHostFilterLabel": "Quelle:",
  "forensicHostFilterAll": "Gesamt",
  "forensicHostFilterAria": "Forensic-Diagramme nach JSONL-Quelle (Host) filtern",
  "forensicHostFilterHint": "Anzeige: Token, Session-Signale und Hit-Limit nur f\u00fcr \u201e{host}\u201c. \u201eAusfall (h)\u201c bleibt der Kalendertag laut Anthropic (status.claude.com), nicht pro Maschine zuordenbar.",
  "forensicTooltipHostHitScope": "Hit-Limit-Balken: nur {host}. Die folgenden Zeilen (Peak, Budget, Hinweis) gelten f\u00fcr den ganzen Tag \u00fcber alle Quellen.",
  "forensicSignalsTooltipOutageDayScope": "Ausfall-Balken: ganzer Kalendertag (Anthropic), nicht Host-spezifisch.",
  "forensicSummaryHostSuffix": " \u00b7 Quelle: {host}",
  "forensicClientHintNone": "Kein Forensic-Flag (f\u00fcr diese Quelle).",
  "forensicClientHintCache": "Cache read \u2265500M \u2014 starkes Session-/Cache-Signal m\u00f6glich.",
  "forensicClientHintHit": "JSONL: Rate-/Limit-/429-\u00e4hnliche Zeilen f\u00fcr diese Quelle.",
  "forensicClientHintPeak": "Deutlich weniger Tokens als am Peak-Tag ({peak}) bei viel Output/Calls \u2014 Heuristik wie token_forensics.",
  "reportBtnTitle": "Forensic Report als Markdown erzeugen",
  "liveConnected": "Live ({time})",
  "dayPickerLabel": "Karten & Tabelle (Tag wählen)",
  "dayPickerAria": "Tag für Karten und Tagesdetail",
  "cardDayOutput": "Tag Output",
  "cardDayCacheRead": "Tag Cache Read",
  "cardCacheOutSub": "Cache:Out {ratio}x",
  "cardDayTotal": "Tag Total",
  "cardCallsActiveSub": "{calls} Aufrufe, {hours}h aktiv",
  "cardHitDay": "Hit Limit (Tag)",
  "cardHitDaySub": "JSONL-Zeilen Limit/429 an diesem Tag",
  "cardHitAll": "Hit Limit (alle Tage)",
  "cardHitAllSub": "Summe über alle Tage",
  "cardOverhead": "Tag Overhead",
  "cardOverheadSub": "Tokens pro Output-Token",
  "cardPeak": "Peak-Tag Total",
  "cardPeakSub": "{date} (höchste Claude-Nutzung im Log)",
  "cardAllOut": "Gesamt Output",
  "cardAllOutSub": "{days} Tage mit Nutzung",
  "cardAllCache": "Gesamt Cache Read",
  "cardAllCacheSub": "{pct} vom Total",
  "cardSessionSignals": "Session-Signale (JSONL)",
  "cardSessionSignalsSub": "continue {c} · resume {r} · retry {y} · interrupt {i} — heuristischer Textabgleich",
  "chartSessionSignalsTitle": "Session-Signale in den Logs (pro Tag)",
  "chartSessionSignalsBlurb": "Anzahl JSONL-Zeilen mit --continue/--resume, Retry-/429-Mustern oder Interrupt/Abbruch (heuristisch; kein API-Nachweis).",
  "sigContinue": "continue",
  "sigResume": "resume",
  "sigRetry": "retry",
  "sigInterrupt": "interrupt",
  "cardHostParen": " (Tag)",
  "cardHostSub": "{out} out · {calls} calls · HitLim {hit}",
  "fcForensicDay": "Forensic (gew. Tag)",
  "fcImpl": "Impl. cap @90%",
  "fcImplSub": "total/0.9 (Rechenbeispiel, nicht UI-90%/100%)",
  "fcBudget": "Budget-Reduktion",
  "fcBudgetSub": "peak / (limitTag/0.9) — Peak & Limit automatisch erkannt (token_forensics.js)",
  "forensicSummaryLine": "Forensic — {pick}: {fc} | Impl@90%: {impl} | Budget ~{bud}× | Peak {peak}",
  "chartDailyToken": "Täglicher Token-Verbrauch",
  "chartCacheRatio": "Cache:Output-Verhältnis (niedriger = effizienter)",
  "chartHostTitle": "Total-Tokens pro Tag nach Host (gestapelt)",
  "chartHostBlurb": "Summe Input+Output+Cache Read+Cache Create je Host. Balkenhöhe entspricht dem Gesamttag (wie „Täglicher Token-Verbrauch“).",
  "chartOutPerHour": "Output pro aktiver Stunde",
  "chartSubCachePct": "Subagent-Cache % vom Gesamt-Cache",
  "chartTooltipSubCacheOfDay": "vom Tages-Cache-Read",
  "chartTooltipSubCacheStackTotal": "Balkenhöhe ≈ Sub-Cache-Anteil Tag: {pct}%",
  "chartDS_cacheRead": "Cache Read",
  "chartDS_output": "Output",
  "chartDS_cacheCreate": "Cache Create",
  "chartLineCacheOut": "Cache:Output",
  "chartTooltipCoDay": "C:O (Tag): {ratio}x",
  "chartTooltipOutCacheDay": "Output {out} · Cache Read {cache}",
  "chartTooltipCoHostLine": "{host}: C:O {ratio}x",
  "chartOutPerHLabel": "Output/h",
  "hostStackFooter": "Summe (alle Hosts): ",
  "forensicDS_hitLimit": "Hit Limit (JSONL-Zeilen)",
  "forensicDS_score": "Forensic-Score (3=? · 2=HIT · 1=<<P)",
  "forensicAxisHit": "Hit Limit (rot)",
  "forensicAxisCounts": "JSONL-Zeilen (Signale + Hit)",
  "forensicAxisForensic": "Forensic",
  "serviceAxisHours": "Stunden",
  "serviceTooltipSessionSigHourNote": "Stundeneinteilung: Retry \u2192 rot, Interrupt \u2192 gelb (JSONL-Zeitstempel); Continue/Resume bleiben in sauberer Arbeit. Gestapelte Balken z\u00e4hlen nur Stunden mit Token-Nutzung.",
  "serviceTooltipSlideoutHint": "Extension-Release, Model-Wechsel, Outage-Report & Forensic: Klick auf \u25b2 / \u25c7 oder Eintrag im Live-Panel \u2192 rechtes Slideout.",
  "tooltipVsPeak": "vs Peak: ",
  "tooltipImpl90": "Impl@90%: ",
  "scanSourcesPrefix": "Scan-Quellen: ",
  "statePathsTitle": "Lokale Dashboard-Dateien (~/.claude):",
  "statePathDay": "Tages-Cache: ",
  "statePathTodayIndex": "JSONL-Heute-Index (mtime): ",
  "statePathReleases": "GitHub-Releases: ",
  "statePathMarketplace": "Marketplace-Versionen: ",
  "statePathOutage": "Outage-Cache: ",
  "githubTokenLabel": "GitHub PAT (nur diese Browser-Sitzung, sessionStorage):",
  "githubTokenSave": "Speichern",
  "githubTokenClear": "Entfernen",
  "githubTokenRefreshReleases": "Releases laden",
  "githubTokenSavedLine": "GitHub PAT (gespeichert) — Wert wird nicht angezeigt.",
  "githubTokenHint": "Das Token wird als Header X-GitHub-Token nur an diesen Dashboard-Server gesendet; der Server ruft damit die GitHub-API auf (nicht der Browser direkt). Classisches PAT reicht für öffentliche Release-Metadaten. Tab schließen löscht die Sitzung.",
  "githubTokenSaved": "Gespeichert.",
  "githubTokenStoredPersistent": "PAT aktiv (nur diese Registerkarte). Vollständiger Neu-Scan startet nicht.",
  "githubTokenCleared": "Entfernt. Es gilt wieder GITHUB_TOKEN/GH_TOKEN auf dem Server, falls gesetzt.",
  "githubReleasesRefreshOk": "Release-Aktualisierung gestartet (Hintergrund).",
  "githubReleasesRefreshFail": "Release-Aktualisierung fehlgeschlagen (Netzwerk oder 401 Admin-Token).",
  "marketplaceRefreshLabel": "VS Marketplace (Extension-Versionen)",
  "marketplaceRefreshOk": "Marketplace-Abfrage gestartet (Hintergrund, siehe Server-Log). Nach Erfolg SSE/Timeline.",
  "marketplaceRefreshFail": "Marketplace fehlgeschlagen (Netzwerk, Timeout oder 401 Admin-Token).",
  "forensicChartTitle": "Forensic & Hit Limit pro Tag",
  "forensicChartBlurbHtml": "Ein <strong>gestapelter Balken</strong> pro Tag: <strong>Hit-Limit</strong>-Zeilen in JSONL. <strong style=\"color:#f59e0b\">Linie</strong> = Forensic-Score (3=? \u00b7 2=HIT \u00b7 1=&lt;&lt;P). Darunter: <strong>Session-Signale pro Tag</strong> (gestapelt, <strong>Ausfallstunden</strong> als oberstes Segment) + <strong>Cache Read</strong> als Linie \u2014 siehe n\u00e4chstes Diagramm.",
  "forensicSignalsChartTitle": "Session-Signale & Ausfall (gestapelt) + Cache Read",
  "forensicSignalsBlurbHtml": "Pro <strong>Tag</strong>: <strong>unten \u2192 oben</strong> continue, resume, retry, interrupt, dann <strong>Ausfall (h)</strong> als <strong>oberstes</strong> Balkensegment (damit er nicht unter gro\u00dfen Interrupt-Anteilen \u2018versinkt\u2019). Balkenh\u00f6he der Ausfallzeit ist <strong>skaliert</strong> (Stunden vs. JSONL-Z\u00e4hler); der <strong>Tooltip</strong> zeigt echte Stunden. <strong>Lila Linie</strong> = Cache Read (eigene rechte Skala) \u2014 Tages-Heuristik mit Interrupts/Ausfall, kein Kausalbeweis. Tooltip erg\u00e4nzt Output/Cache und C:O.",
  "forensicSignalsAxisLines": "Signale + Ausfall (h, Balken skaliert)",
  "forensicSignalsAxisOutage": "Ausfall (h)",
  "forensicSignalsAxisCacheRead": "Cache Read (Tokens)",
  "forensicDS_continueStack": "continue",
  "forensicDS_resumeStack": "resume",
  "forensicDS_retryStack": "retry",
  "forensicDS_interruptStack": "interrupt",
  "forensicDS_outageHoursDay": "Ausfall (h)",
  "forensicSignalsTooltipStackFooter": "Balken: Signale/Tag, oben Ausfall (Tooltip = echte h); lila Linie = Cache Read (eigene Skala).",
  "unifiedAxisTokens": "Tokens",
  "unifiedChartTitle": "Token-Budget & Ausfall-Impact",
  "serviceChartTitle": "Service Impact: Arbeitszeit vs. Ausfall",
  "mainChartsSkelHint": "Platzhalter \u2014 Token-Diagramme erscheinen hier, sobald Nutzungsdaten vorliegen (ohne vollst\u00e4ndigen Cache abwarten zu m\u00fcssen).",
  "serviceBlurb": "<strong style=\"color:rgba(59,130,246,0.8)\">Blau</strong> = saubere Arbeit. <strong style=\"color:rgba(239,68,68,0.8)\">Rot</strong> = Stunden mit API-/Server-Stress: offizieller Ausfall <strong>oder</strong> JSONL-<code>retry</code> zur Uhrzeit des Logeintrags (nicht nur Tages-Summe). <strong style=\"color:rgba(251,191,36,0.8)\">Gelb</strong> = Client-Ausfall <strong>oder</strong> JSONL-<code>interrupt</code> in derselben Stunde. <strong style=\"color:rgba(107,114,128,0.6)\">Grau</strong> = Ausfall ohne Arbeit in diesen Stunden. Continue/Resume z\u00e4hlen weiter als saubere Stunden. <strong>Gestapelte Balken</strong> z\u00e4hlen nur Stunden mit echtem Token-Output (kein Z\u00e4hlen reiner Session-Signale). Tages-Summen der Signale (gestapelt): <strong>Forensic-Bereich</strong>, Diagramm darunter. <strong style=\"color:#8b5cf6\">Lila Linie</strong> = Cache Read (rechte Skala). <strong style=\"color:#22d3ee\">\u25c7</strong> / <strong style=\"color:#4ade80\">\u25b2</strong> = Model- bzw. Extension-Tag (Klick \u2192 <strong>Slideout</strong>: Release-Notes, Outage-Report, Forensic). <strong>Tooltip</strong> nur Balken-/Token-Kurzinfos; <strong>Live</strong>-Panel: Outage-Liste & Extension-Kurzliste.",
  "serviceTooltipSessionSig": "JSONL-Zeilen (c / r / retry / interrupt)",
  "serviceDS_cleanWork": "Saubere Arbeit",
  "serviceDS_affectedServer": "Arbeit bei API-Ausfall (Retries)",
  "serviceDS_affectedClient": "Arbeit bei Client-Bug (kein Token-Impact)",
  "serviceDS_affectedWork": "Arbeit bei Ausfall",
  "serviceDS_outageOnly": "Ausfall (keine Arbeit)",
  "thinkingNote": "\u26a0 Thinking-Tokens (internes Reasoning) erscheinen nicht in der API-Antwort und werden nicht gez\u00e4hlt. Sie belasten wahrscheinlich das Session-Budget.",
  "tableCols": "Datum|Output|Cache Read|V:O|Overhead|Total|Aufrufe|Std.|Hit Limit|Sub%|Sub-Cache%|Out/h",
  "metaScanError": "Scan-Fehler: {msg}",
  "reportBtn": "Forensic Report",
  "reportTitle": "Forensic Report (Markdown)",
  "reportCopy": "Kopieren",
  "reportDownload": "Download .md",
  "reportCopied": "Kopiert!",
  "reportNoData": "Keine Daten — Scan muss zuerst abgeschlossen sein.",
  "outageChartTitle": "Outage-Zeitfenster (status.claude.com)",
  "outageChartBlurbHtml": "Balken zeigen Ausfallzeitfenster (UTC). <strong style=\"color:#f97316\">Orange</strong> = Major, <strong style=\"color:#ef4444\">Rot</strong> = Critical, <strong style=\"color:#facc15\">Gelb</strong> = Minor. Hover für Details.",
  "outageDS_spans": "Ausfall-Zeitspanne",
  "outageAxisHour": "Stunde",
  "outageTotal": "Ausfall gesamt",
  "statusPending": "Status…",
  "statusPendingTip": "Anthropic-Status wird geladen…",
  "statusOutage": "Ausfall!",
  "statusOutageTip": "Aktiver Ausfall bei Anthropic gemeldet (status.claude.com)",
  "statusIncident": "Incident",
  "statusIncidentTip": "Heute wurde ein Incident bei Anthropic gemeldet (bereits behoben)",
  "statusOk": "OK",
  "statusOkTip": "Keine aktuellen Incidents bei Anthropic (status.claude.com)",
  "tooltipOutage": "Ausfall: ",
  "tooltipModelAdded": "Model neu: ",
  "tooltipModelRemoved": "Model entfernt: ",
  "forensicDS_modelChange": "Model-Wechsel",
  "forensicDS_outageHours": "Ausfall (h)",
  "serviceDS_versionChange": "Extension-Update",
  "tooltipVersionUpdate": "Extension: ",
  "serviceTooltipReleaseClock": "Marketplace/Release-Zeit: ",
  "serviceTooltipReleaseUtc": "gebucht auf UTC-Tag (wie JSONL-Datum): ",
  "serviceTooltipReleaseLocal": "lokaler Kalendertag (diese Maschine): ",
  "updateSlideoutClose": "Schließen",
  "updateDotAria": "Extension-Update: Details einblenden",
  "modelDotAria": "Model-Wechsel: Details einblenden",
  "modelSlideoutHeading": "Model-Wechsel",
  "modelSlideoutNoDetail": "Keine Model-Details f\u00fcr diesen Tag.",
  "updateSlideoutHeading": "Extension-Update",
  "updateSlideoutNoDetail": "Keine Versionsdetails für diesen Tag.",
  "updateSlideoutHighlights": "Release-Notes (Auszug)",
  "updateSlideoutHighlightsEmpty": "Noch kein Auszug: der Server lädt fehlende Releases nach dem Scan per HTTPS in ~/.claude/claude-code-releases.json — kurz warten bis SSE aktualisiert, dann Slideout erneut öffnen. Oder direkt auf GitHub:",
  "updateSlideoutGithubReleases": "GitHub-Releases",
  "updateSlideoutStatusHeading": "Anthropic Status / Ausf\u00e4lle (dieser Tag)",
  "updateSlideoutOutageHoursLine": "Ausfall-Zeit: {total} h gesamt (Server {srv} h \u00b7 Client {cli} h)",
  "updateSlideoutOutageIncidents": "Incidents (status.claude.com)",
  "updateSlideoutOutageSpans": "Zeitspannen (UTC, Kalendertag)",
  "updateSlideoutLikelyHit": "Hinweis: Viele Hit-Limit-Zeilen in JSONL \u2014 zeitlicher Zusammenhang mit Ausfall m\u00f6glich (Heuristik).",
  "updateSlideoutIncidentStart": "Start",
  "updateSlideoutIncidentResolved": "Ende",
  "updateSlideoutIncidentOngoing": "laufend / unklar",
  "updateSlideoutForensicHeading": "Forensic (Kurzinfo)",
  "serviceTooltipReleaseGithubHint": "GitHub (Release-Seiten):",
  "timelineTitle": "Arbeitszeit & Ausfälle (Tagesachse 0\u201324h)",
  "timelineBlurbHtml": "<strong style=\"color:rgba(59,130,246,0.7)\">Blau</strong> = Arbeitszeit (erste bis letzte aktive Stunde, Intensität = Opacity). <strong style=\"color:rgba(239,68,68,0.7)\">Rot</strong> = Anthropic-Ausfall. <strong style=\"color:#22d3ee\">\u25c7</strong> = Model-Wechsel. Überlappung = Ausfall während Arbeit.",
  "timelineDS_work": "Arbeitszeit",
  "timelineDS_outage": "Ausfall (status.claude.com)",
  "timelineAxisHour": "Tageszeit (UTC)"
}
