{
  "pageTitle": "Claude Code Nutzungs-Dashboard",
  "heading": "Claude Code Token-Nutzung",
  "subModelsHtml": "Nur <strong>Claude</strong>-Modelle (<code>claude-*</code>) — keine <code>&lt;synthetic&gt;</code>-Zeilen.",
  "langLabel": "Sprache",
  "ariaLangGroup": "Sprache wählen",
  "liveFilesAria": "Gescannte JSONL-Dateien",
  "liveFilesHint": "Pro Zeile: Quelle · Pfad (~ = User-Home dieses Rechners). Hover oder Fokus (Tab) hält die Liste offen.",
  "liveFilesHead0": "Gescannte JSONL",
  "liveFilesHeadN": "Gescannte JSONL ({n})",
  "scanStill": "Scan läuft noch…",
  "noJsonlList": "Keine .jsonl in den konfigurierten Scan-Wurzeln (siehe Datenquelle / CLAUDE_USAGE_EXTRA_BASES).",
  "sseDisconnected": "Getrennt — verbinde erneut…",
  "liveTriggerScanning": "Live — Scan läuft",
  "liveTriggerZero": "0 JSONL-Dateien",
  "liveTriggerMany": "{n} JSONL — Hover oder Tab für Liste; Klick hält auf Touch offen",
  "metaScanning": "Scanne ~/.claude/projects im Hintergrund… Inhalt folgt per Live-Update (SSE). Dateien werden in kleinen Batches gelesen.",
  "metaForensicScanning": "Forensic — Scan läuft…",
  "metaForensicNoteFirst": "Erster Lauf nach Serverstart; danach alle {sec}s im Hintergrund.",
  "liveWaitData": "Live — warte auf Daten…",
  "metaNoFiles": "Keine Daten: 0 .jsonl-Dateien in den Scan-Wurzeln (~/.claude/projects ggf. + CLAUDE_USAGE_EXTRA_BASES). Ohne passende Logs bleiben Karten und Tabellen leer.",
  "metaNoUsage": "Keine Tageswerte: {files} Datei(en) gelesen, aber keine usage-Zeilen mit Modell claude-*.",
  "forensicSummaryNoData": "Forensic (token_forensics) — keine Daten",
  "metaParsed": "Parsed {files} Log-Dateien | Stand: {time} | Auto-Refresh alle {sec}s",
  "metaParsedInProgress": "Einlesen {done}/{total} Log-Dateien | Stand: {time} | Auto-Refresh alle {sec}s",
  "metaChartsHint": "| Karten: gewählter Tag (Dropdown), Diagramme: alle Tage.",
  "metaDetailsSummaryLine": "{files} Log-Dateien · alle {sec}s — aufklappen für Hinweise & Datenstand",
  "metaSummaryScanning": "Scan läuft… — aufklappen",
  "metaDetailsScanProgress": "{done}/{total} Log-Dateien · alle {sec}s — Daten laufen ein (live)",
  "metaScanningExpanded": "Scan: {done}/{total} Log-Dateien gelesen (alle {sec}s Refresh). Diagramme erscheinen mit ersten Treffern — noch nicht final.",
  "metaSummaryNoFiles": "Keine .jsonl in den Scan-Wurzeln — aufklappen",
  "metaSummaryNoUsage": "Keine Nutzung in {files} Datei(en) — aufklappen",
  "calTodaySuffix": " — Kalender heute",
  "zeroLogsSuffix": " (0 in Logs)",
  "dayPickerHintZero": "Kalender-heute: 0 Tokens in den Logs — älteren Tag mit Nutzung wählen.",
  "limitSourceTooltip": "Session- und Rate-Limits setzt Anthropic/Claude Code; JSONL enthält meist nur erfolgreiche API-Nutzung (usage). Hit Limit zählt Zeilen mit typischen Limit-/Fehlertexten.",
  "dailyDetailPrefix": "Tagesdetail — ",
  "dailyDetailClearHost": "Alle Hosts",
  "dailyDetailHostRowTitle": "Klick: nur dieser Host im Tagesdetail",
  "dailyDetailFilteredRowTitle": "Klick: wieder alle Hosts",
  "liveConnected": "Live ({time})",
  "dayPickerLabel": "Karten & Tabelle (Tag wählen)",
  "dayPickerAria": "Tag für Karten und Tagesdetail",
  "cardDayOutput": "Tag Output",
  "cardDayCacheRead": "Tag Cache Read",
  "cardCacheOutSub": "Cache:Out {ratio}x",
  "cardDayTotal": "Tag Total",
  "cardCallsActiveSub": "{calls} Aufrufe, {hours}h aktiv",
  "cardHitDay": "Hit Limit (Tag)",
  "cardHitDaySub": "JSONL-Zeilen Limit/429 an diesem Tag",
  "cardHitAll": "Hit Limit (alle Tage)",
  "cardHitAllSub": "Summe über alle Tage",
  "cardOverhead": "Tag Overhead",
  "cardOverheadSub": "Tokens pro Output-Token",
  "cardPeak": "Peak-Tag Total",
  "cardPeakSub": "{date} (höchste Claude-Nutzung im Log)",
  "cardAllOut": "Gesamt Output",
  "cardAllOutSub": "{days} Tage mit Nutzung",
  "cardAllCache": "Gesamt Cache Read",
  "cardAllCacheSub": "{pct} vom Total",
  "cardHostParen": " (Tag)",
  "cardHostSub": "{out} out · {calls} calls · HitLim {hit}",
  "fcForensicDay": "Forensic (gew. Tag)",
  "fcImpl": "Impl. cap @90%",
  "fcImplSub": "total/0.9 (Rechenbeispiel, nicht UI-90%/100%)",
  "fcBudget": "Budget-Reduktion",
  "fcBudgetSub": "peak / (limitTag/0.9) — Peak & Limit automatisch erkannt (token_forensics.js)",
  "forensicSummaryLine": "Forensic — {pick}: {fc} | Impl@90%: {impl} | Budget ~{bud}× | Peak {peak}",
  "chartDailyToken": "Täglicher Token-Verbrauch",
  "chartCacheRatio": "Cache:Output-Verhältnis (niedriger = effizienter)",
  "chartHostTitle": "Total-Tokens pro Tag nach Host (gestapelt)",
  "chartHostBlurb": "Summe Input+Output+Cache Read+Cache Create je Host. Balkenhöhe entspricht dem Gesamttag (wie „Täglicher Token-Verbrauch“).",
  "chartOutPerHour": "Output pro aktiver Stunde",
  "chartSubCachePct": "Subagent-Cache % vom Gesamt-Cache",
  "chartTooltipSubCacheOfDay": "vom Tages-Cache-Read",
  "chartTooltipSubCacheStackTotal": "Balkenhöhe ≈ Sub-Cache-Anteil Tag: {pct}%",
  "chartDS_cacheRead": "Cache Read",
  "chartDS_output": "Output",
  "chartDS_cacheCreate": "Cache Create",
  "chartLineCacheOut": "Cache:Output",
  "chartTooltipCoDay": "C:O (Tag): {ratio}x",
  "chartTooltipOutCacheDay": "Output {out} · Cache Read {cache}",
  "chartTooltipCoHostLine": "{host}: C:O {ratio}x",
  "chartOutPerHLabel": "Output/h",
  "hostStackFooter": "Summe (alle Hosts): ",
  "forensicDS_hitLimit": "Hit Limit (JSONL-Zeilen)",
  "forensicDS_score": "Forensic-Score (3=? · 2=HIT · 1=<<P)",
  "forensicAxisHit": "Hit Limit (rot)",
  "forensicAxisForensic": "Forensic",
  "tooltipVsPeak": "vs Peak: ",
  "tooltipImpl90": "Impl@90%: ",
  "scanSourcesPrefix": "Scan-Quellen: ",
  "statePathsTitle": "Lokale Dashboard-Dateien (~/.claude):",
  "statePathDay": "Tages-Cache: ",
  "statePathReleases": "GitHub-Releases: ",
  "statePathMarketplace": "Marketplace-Versionen: ",
  "statePathOutage": "Outage-Cache: ",
  "forensicChartTitle": "Forensic & Hit Limit pro Tag",
  "forensicChartBlurbHtml": "Gestapelte Balken: <strong style=\"color:rgba(59,130,246,0.85)\">Blau</strong> = Output (Nutzen), <strong style=\"color:rgba(139,92,246,0.7)\">Lila</strong> = Cache Read (Overhead), <strong style=\"color:rgba(220,38,38,0.7)\">Rot</strong> = Cache Read bei Ausfall. D\u00fcnne Balken rechts: <strong style=\"color:#f97316\">Ausfall-Stunden</strong> (0\u201324h). R\u00f6tlicher Hintergrund = Anthropic-Ausfall an diesem Tag. <strong style=\"color:#22d3ee\">\u25c7</strong> = Model-Wechsel.",
  "unifiedAxisTokens": "Tokens",
  "unifiedChartTitle": "Token-Budget & Ausfall-Impact",
  "serviceChartTitle": "Service Impact: Arbeitszeit vs. Ausfall",
  "serviceBlurb": "<strong style=\"color:rgba(59,130,246,0.8)\">Blau</strong> = saubere Arbeit. <strong style=\"color:rgba(239,68,68,0.8)\">Rot</strong> = Arbeit bei API-Ausfall (Retries). <strong style=\"color:rgba(251,191,36,0.8)\">Gelb</strong> = Arbeit bei Client-Bug (kein Token-Impact). <strong style=\"color:rgba(107,114,128,0.6)\">Grau</strong> = Ausfall ohne Arbeit. <strong style=\"color:#8b5cf6\">Lila Linie</strong> = Cache Read. <strong style=\"color:#22d3ee\">\u25c7</strong> = Model-Wechsel. <strong style=\"color:#4ade80\">\u25b2</strong> = Extension-Update.",
  "serviceDS_cleanWork": "Saubere Arbeit",
  "serviceDS_affectedServer": "Arbeit bei API-Ausfall (Retries)",
  "serviceDS_affectedClient": "Arbeit bei Client-Bug (kein Token-Impact)",
  "serviceDS_affectedWork": "Arbeit bei Ausfall",
  "serviceDS_outageOnly": "Ausfall (keine Arbeit)",
  "serviceAxisHours": "Stunden",
  "thinkingNote": "\u26a0 Thinking-Tokens (internes Reasoning) erscheinen nicht in der API-Antwort und werden nicht gez\u00e4hlt. Sie belasten wahrscheinlich das Session-Budget.",
  "tableCols": "Datum|Output|Cache Read|V:O|Overhead|Total|Aufrufe|Std.|Hit Limit|Sub%|Sub-Cache%|Out/h",
  "metaScanError": "Scan-Fehler: {msg}",
  "reportBtn": "Forensic Report",
  "reportTitle": "Forensic Report (Markdown)",
  "reportCopy": "Kopieren",
  "reportDownload": "Download .md",
  "reportCopied": "Kopiert!",
  "reportNoData": "Keine Daten — Scan muss zuerst abgeschlossen sein.",
  "outageChartTitle": "Outage-Zeitfenster (status.claude.com)",
  "outageChartBlurbHtml": "Balken zeigen Ausfallzeitfenster (UTC). <strong style=\"color:#f97316\">Orange</strong> = Major, <strong style=\"color:#ef4444\">Rot</strong> = Critical, <strong style=\"color:#facc15\">Gelb</strong> = Minor. Hover für Details.",
  "outageDS_spans": "Ausfall-Zeitspanne",
  "outageAxisHour": "Stunde",
  "outageTotal": "Ausfall gesamt",
  "statusPending": "Status…",
  "statusPendingTip": "Anthropic-Status wird geladen…",
  "statusOutage": "Ausfall!",
  "statusOutageTip": "Aktiver Ausfall bei Anthropic gemeldet (status.claude.com)",
  "statusIncident": "Incident",
  "statusIncidentTip": "Heute wurde ein Incident bei Anthropic gemeldet (bereits behoben)",
  "statusOk": "OK",
  "statusOkTip": "Keine aktuellen Incidents bei Anthropic (status.claude.com)",
  "tooltipOutage": "Ausfall: ",
  "tooltipModelAdded": "Model neu: ",
  "tooltipModelRemoved": "Model entfernt: ",
  "forensicDS_modelChange": "Model-Wechsel",
  "forensicDS_outageHours": "Ausfall (h)",
  "serviceDS_versionChange": "Extension-Update",
  "tooltipVersionUpdate": "Extension: ",
  "serviceTooltipReleaseClock": "Marketplace/Release-Zeit: ",
  "serviceTooltipReleaseUtc": "gebucht auf UTC-Tag (wie JSONL-Datum): ",
  "serviceTooltipReleaseLocal": "lokaler Kalendertag (diese Maschine): ",
  "timelineTitle": "Arbeitszeit & Ausfälle (Tagesachse 0\u201324h)",
  "timelineBlurbHtml": "<strong style=\"color:rgba(59,130,246,0.7)\">Blau</strong> = Arbeitszeit (erste bis letzte aktive Stunde, Intensität = Opacity). <strong style=\"color:rgba(239,68,68,0.7)\">Rot</strong> = Anthropic-Ausfall. <strong style=\"color:#22d3ee\">\u25c7</strong> = Model-Wechsel. Überlappung = Ausfall während Arbeit.",
  "timelineDS_work": "Arbeitszeit",
  "timelineDS_outage": "Ausfall (status.claude.com)",
  "timelineAxisHour": "Tageszeit (UTC)"
}
