{
  "pageTitle": "Claude Code 사용량 대시보드",
  "heading": "Claude Code Token 사용량",
  "subModelsHtml": "<strong>Claude</strong> 모델(<code>claude-*</code>)만 집계 — <code>&lt;synthetic&gt;</code> 라인 제외.",
  "langLabel": "언어",
  "ariaLangGroup": "언어 선택",
  "liveFilesAria": "스캔된 JSONL 파일",
  "livePanelAria": "실시간 패널: 스캔된 JSONL, Anthropic 장애, 확장 프로그램 업데이트",
  "liveFilesHint": "\"Live\"를 클릭하여 패널을 열거나 닫습니다. 각 줄: 소스 · 경로 (~ = 이 머신의 홈 디렉토리).",
  "liveFilesHead0": "스캔된 JSONL",
  "liveFilesHeadN": "스캔된 JSONL ({n})",
  "scanStill": "스캔 진행 중…",
  "noJsonlList": "설정된 스캔 경로에 .jsonl 파일 없음 (데이터 소스 / CLAUDE_USAGE_EXTRA_BASES 확인).",
  "sseDisconnected": "연결 끊김 — 재연결 중…",
  "liveTriggerScanning": "Live — 스캔 중",
  "liveTriggerZero": "JSONL 파일 0개",
  "liveTriggerMany": "JSONL {n}개 — 클릭하여 Live 패널 열기",
  "liveOutageHead": "장애 (status.claude.com)",
  "liveOutageEmpty": "현재 범위에 장애 기록 없음.",
  "liveExtHead": "확장 프로그램 업데이트 (Claude Code)",
  "liveExtEmpty": "해당 기간에 확장 프로그램 변경 없음.",
  "liveExtOpenAria": "확장 프로그램 업데이트 상세 보기",
  "metaShellReady": "레이아웃 준비 완료 — 페이지 구조가 이미 로드되었습니다. 라이브 스캔이 로그 데이터를 스트리밍하며, 일별 데이터가 파싱되면 차트가 채워집니다 (디스크 캐시 완료를 기다릴 필요 없음).",
  "metaDetailsSummaryDefault": "메타 및 데이터 소스",
  "dayPickerScanning": "스캔 중…",
  "dayPickerNoData": "선택 가능한 날짜 없음",
  "metaScanning": "백그라운드에서 ~/.claude/projects 스캔 중… SSE를 통해 업데이트됩니다. 파일을 소규모 배치로 읽는 중.",
  "metaForensicScanning": "Forensic — 스캔 중…",
  "metaForensicNoteFirst": "서버 시작 후 첫 실행; 이후 {sec}초마다 백그라운드 실행.",
  "liveWaitData": "Live — 데이터 대기 중…",
  "metaNoFiles": "데이터 없음: 스캔 경로(~/.claude/projects 및 CLAUDE_USAGE_EXTRA_BASES)에 .jsonl 파일 0개. 로그가 없으면 카드와 테이블이 비어 있습니다.",
  "metaNoUsage": "일별 데이터 없음: {files}개 파일을 읽었지만 claude-* 모델의 사용 내역이 없습니다.",
  "forensicSummaryNoData": "Forensic (token_forensics) — 데이터 없음",
  "metaParsed": "{files}개 로그 파일 파싱 완료 | 마지막 업데이트: {time} | {sec}초마다 자동 갱신",
  "metaParsedInProgress": "{done}/{total}개 로그 파일 로딩 중 | 마지막 업데이트: {time} | {sec}초마다 자동 갱신",
  "metaChartsHint": "| 카드 & 테이블: 선택한 날짜. 메인 차트: 아래 \"전체 기간 / 24시간\" 전환.",
  "metaChartsHintHourly": "24시간 모드: 하루를 시간 단위로 표시; Token 막대는 시간별 API 이벤트 비율로 추정.",
  "mainChartsScopeLabel": "메인 차트:",
  "mainChartsScopeAria": "차트: 전체 기간 또는 선택한 날짜의 시간별",
  "mainChartsScopeTimeline": "전체 기간",
  "mainChartsScopeHourly": "24시간 (선택한 날)",
  "chartDailyTokenHourly": "시간별 Token (추정)",
  "chartCacheRatioHourly": "시간별 Cache:Output (추정)",
  "chartOutPerHourHourly": "시간별 API 이벤트",
  "chartSubCachePctHourly": "시간별 세션 신호",
  "chartTooltipHourlyTokenEst": "Token 행: 일별 합계 × (해당 시간 이벤트 / 일별 이벤트 합계).",
  "chartHourlyApiEventsLabel": "API 이벤트",
  "metaDetailsSummaryLine": "{files}개 로그 파일 · {sec}초마다 — 펼쳐서 상세 확인",
  "metaSummaryScanning": "스캔 중… — 펼치기",
  "metaDetailsScanProgress": "{done}/{total}개 로그 파일 · {sec}초마다 — 실시간 로딩 중",
  "metaScanningExpanded": "스캔: {done}/{total}개 로그 파일 읽는 중 ({sec}초마다 갱신). 데이터가 들어오면 차트가 나타납니다 — 아직 최종 결과가 아닙니다.",
  "metaSummaryNoFiles": "스캔 경로에 .jsonl 없음 — 펼치기",
  "metaSummaryNoUsage": "{files}개 파일에서 사용 내역 없음 — 펼치기",
  "calTodaySuffix": " — 오늘",
  "zeroLogsSuffix": " (로그 0건)",
  "dayPickerHintZero": "오늘: 로그에 Token 0건 — 사용 내역이 있는 다른 날짜를 선택하세요.",
  "limitSourceTooltip": "Anthropic / Claude Code가 세션 및 Rate Limit을 적용합니다. JSONL에는 주로 성공한 API 사용 내역만 표시됩니다. Hit Limit은 일반적인 제한/오류 패턴과 일치하는 라인을 집계합니다.",
  "dailyDetailPrefix": "일별 상세 — ",
  "dailyDetailClearHost": "전체 호스트",
  "dailyDetailHostRowTitle": "클릭: 이 호스트만 일별 상세에 표시",
  "dailyDetailFilteredRowTitle": "클릭: 전체 호스트 다시 표시",
  "forensicHostFilterLabel": "소스:",
  "forensicHostFilterAll": "전체",
  "forensicHostFilterAria": "JSONL 소스(호스트)별 Forensic 차트 필터",
  "forensicHostFilterHint": "Token, 세션 신호, Hit Limit을 \"{host}\"만 표시합니다. 장애 시간은 Anthropic(status.claude.com) 기준 전체 날짜이며 개별 머신에 귀속되지 않습니다.",
  "forensicTooltipHostHitScope": "Hit Limit 막대: {host}만. 아래 라인(Peak, 예상 Budget, 참고)은 모든 소스를 합산한 전체 날짜 기준입니다.",
  "forensicSignalsTooltipOutageDayScope": "장애 막대: 전체 날짜(Anthropic), 호스트별이 아님.",
  "forensicSummaryHostSuffix": " · 소스: {host}",
  "forensicClientHintNone": "Forensic 플래그 없음 (이 소스 기준).",
  "forensicClientHintCache": "Cache Read ≥500M — 높은 세션/캐시 신호 가능성.",
  "forensicClientHintHit": "JSONL: 이 소스의 Rate/Limit/429 유사 라인.",
  "forensicClientHintPeak": "Peak 일({peak}) 대비 현저히 적은 Token, Output/Calls는 상당 — token_forensics와 동일한 휴리스틱.",
  "reportBtnTitle": "Forensic 보고서를 Markdown으로 생성",
  "liveConnected": "Live ({time})",
  "dayPickerLabel": "카드 & 테이블 (날짜 선택)",
  "dayPickerAria": "카드 및 일별 상세용 날짜",
  "cardDayOutput": "일별 Output",
  "cardDayCacheRead": "일별 Cache Read",
  "cardCacheOutSub": "Cache:Out {ratio}x",
  "cardDayTotal": "일별 합계",
  "cardCallsActiveSub": "{calls}회 호출, {hours}시간 활동",
  "cardHitDay": "Hit Limit (당일)",
  "cardHitDaySub": "해당일 JSONL의 Limit/429 라인",
  "cardHitAll": "Hit Limit (전체)",
  "cardHitAllSub": "전체 기간 합산",
  "cardUptime": "Service Uptime",
  "cardUptimeSub": "{days}일간 (major_outage만)",
  "cardServiceQuality": "Service Quality",
  "cardServiceQualitySub": "{days}일간 (crit+major+minor)",
  "cardOverhead": "일별 Overhead",
  "cardOverheadSub": "Output Token당 전체 Token",
  "cardPeak": "Peak 일 합계",
  "cardPeakSub": "{date} (로그 중 최대 Claude 사용량)",
  "cardAllOut": "누적 Output",
  "cardAllOutSub": "사용 내역이 있는 {days}일",
  "cardAllCache": "누적 Cache Read",
  "cardAllCacheSub": "전체의 {pct}",
  "cardSessionSignals": "세션 신호 (JSONL)",
  "cardSessionSignalsSub": "continue {c} · resume {r} · retry {y} · interrupt {i} — 휴리스틱 텍스트 매칭",
  "tokenStatsSummary": "{date} — {out} Output · {cache} Cache · {overhead} Overhead",
  "chartSessionSignalsTitle": "로그의 세션 신호 (일별)",
  "chartSessionSignalsBlurb": "--continue/--resume, retry/429 패턴, 또는 interrupt/cancel과 일치하는 JSONL 라인 수 (휴리스틱; API 정확치 아님).",
  "sigContinue": "continue",
  "sigResume": "resume",
  "sigRetry": "retry",
  "sigInterrupt": "interrupt",
  "cardHostParen": " (당일)",
  "cardHostSub": "{out} out · {calls} calls · HitLim {hit}",
  "fcForensicDay": "Forensic (선택한 날)",
  "fcImpl": "Impl. cap @90%",
  "fcImplSub": "total/0.9 (예시, Claude UI 90%/100%와 다름)",
  "fcBudget": "Budget 감소",
  "fcBudgetSub": "peak / (limitDay/0.9) — Peak & Limit 자동 감지 (token_forensics.js)",
  "forensicSummaryLine": "Forensic — {pick}: {fc} | Impl@90%: {impl} | Budget ~{bud}x | Peak {peak}",
  "chartDailyToken": "일별 Token 소비량",
  "chartCacheRatio": "Cache:Output 비율 (낮을수록 효율적)",
  "chartHostTitle": "호스트별 일별 Total Token (누적)",
  "chartHostBlurb": "호스트별 Input+Output+Cache Read+Cache Create 합계. 막대 높이는 전체 일별 합계와 동일.",
  "chartOutPerHour": "활동 시간당 Output",
  "chartSubCachePct": "전체 Cache 중 Subagent Cache %",
  "chartTooltipSubCacheOfDay": "일별 Cache Read 중",
  "chartTooltipSubCacheStackTotal": "막대 높이 ≈ 일별 Sub-Cache 비율: {pct}%",
  "chartDS_cacheRead": "Cache Read",
  "chartDS_output": "Output",
  "chartDS_cacheCreate": "Cache Create",
  "chartLineCacheOut": "Cache:Output",
  "chartTooltipCoDay": "C:O (당일): {ratio}x",
  "chartTooltipOutCacheDay": "Output {out} · Cache Read {cache}",
  "chartTooltipCoHostLine": "{host}: C:O {ratio}x",
  "chartOutPerHLabel": "Output/h",
  "hostStackFooter": "합계 (전체 호스트): ",
  "forensicDS_hitLimit": "Hit Limit (JSONL 라인)",
  "forensicDS_score": "Forensic 점수 (3=? · 2=HIT · 1=<<P)",
  "forensicAxisHit": "Hit Limit (빨강)",
  "forensicAxisCounts": "JSONL 라인 (신호 + Hit)",
  "forensicAxisForensic": "Forensic",
  "serviceAxisHours": "시간",
  "serviceTooltipSessionSigHourNote": "시간별: retry → 빨강, interrupt → 노랑 (JSONL 타임스탬프); continue/resume는 정상 작업으로 분류. 누적 막대는 Token 사용이 있는 시간만 집계.",
  "serviceTooltipSlideoutHint": "Extension 릴리스, 모델 변경, 장애 보고서 & Forensic: ▲ / ◇ 또는 Live 패널의 항목 클릭 → 우측 슬라이드아웃.",
  "tooltipVsPeak": "vs Peak: ",
  "tooltipImpl90": "Impl@90%: ",
  "scanSourcesPrefix": "스캔 소스: ",
  "statePathsTitle": "로컬 대시보드 파일 (~/.claude):",
  "statePathDay": "일별 캐시: ",
  "statePathTodayIndex": "JSONL 오늘 인덱스 (mtime): ",
  "statePathReleases": "GitHub 릴리스: ",
  "statePathMarketplace": "Marketplace 버전: ",
  "statePathOutage": "장애 캐시: ",
  "githubTokenLabel": "GitHub PAT (이 브라우저 탭에서만, sessionStorage):",
  "githubTokenSave": "저장",
  "githubTokenClear": "삭제",
  "githubTokenRefreshReleases": "릴리스 가져오기",
  "githubTokenSavedLine": "GitHub PAT (저장됨) — 값은 표시되지 않습니다.",
  "githubTokenHint": "Token은 X-GitHub-Token 헤더로 이 대시보드 서버에만 전송됩니다. 서버가 GitHub API를 호출합니다 (브라우저가 직접 호출하지 않음). 공개 릴리스 메타데이터에는 Classic PAT이면 충분합니다. 탭을 닫으면 삭제됩니다.",
  "githubTokenSaved": "저장됨.",
  "githubTokenStoredPersistent": "PAT 활성 (이 탭에서만). 전체 JSONL 재스캔은 실행되지 않습니다.",
  "githubTokenCleared": "삭제됨. 서버에 설정된 GITHUB_TOKEN/GH_TOKEN이 있으면 해당 값으로 대체됩니다.",
  "githubReleasesRefreshOk": "릴리스 갱신 시작 (백그라운드).",
  "githubReleasesRefreshFail": "릴리스 갱신 실패 (네트워크 또는 Admin Token 오류).",
  "marketplaceRefreshLabel": "VS Marketplace (확장 프로그램 버전)",
  "marketplaceRefreshOk": "Marketplace 조회 시작 (백그라운드, 서버 로그 참조). 완료 시 SSE/Timeline 업데이트.",
  "marketplaceRefreshFail": "Marketplace 조회 실패 (네트워크, 타임아웃 또는 401 Admin Token).",
  "forensicChartTitle": "일별 Forensic & Hit Limit",
  "forensicChartBlurbHtml": "일별 <strong>누적 막대</strong>: <strong>Hit Limit</strong> JSONL 라인 수. <strong style=\"color:#f59e0b\">라인</strong> = Forensic 점수 (3=? · 2=HIT · 1=&lt;&lt;P). 아래: <strong>일별 세션 신호</strong> (누적, <strong>장애 시간</strong>이 <strong>최상단</strong> 세그먼트) + <strong>Cache Read</strong> 라인 — 다음 차트 참조.",
  "forensicSignalsChartTitle": "세션 신호 & 장애 (누적) + Cache Read",
  "forensicSignalsBlurbHtml": "<strong>일별</strong>: <strong>아래 → 위</strong> continue, resume, retry, interrupt, 그 위에 <strong>장애(h)</strong>가 <strong>최상단</strong> 막대 세그먼트 (큰 interrupt 아래 묻히지 않도록). 장애 막대 높이는 <strong>스케일링</strong>됨 (시간 vs. JSONL 카운트); <strong>툴팁</strong>에서 실제 시간 표시. <strong>보라색 라인</strong> = Cache Read (별도 우측 축) — 일별 휴리스틱으로 interrupt/장애와 비교, 인과 관계 증명 아님. 툴팁에 Output/Cache와 C:O 추가.",
  "forensicSignalsAxisLines": "신호 + 장애 (h, 막대 스케일링)",
  "forensicSignalsAxisOutage": "장애 (h)",
  "forensicSignalsAxisCacheRead": "Cache Read (Token)",
  "forensicDS_continueStack": "continue",
  "forensicDS_resumeStack": "resume",
  "forensicDS_retryStack": "retry",
  "forensicDS_interruptStack": "interrupt",
  "forensicDS_outageHoursDay": "장애 (h)",
  "forensicSignalsTooltipStackFooter": "막대: 일별 신호, 최상단 장애 (툴팁 = 실제 h); 보라색 라인 = Cache Read (별도 축).",
  "unifiedAxisTokens": "Token",
  "unifiedChartTitle": "Token Budget & 장애 영향",
  "serviceChartTitle": "Service 영향: 작업 시간 vs. 장애",
  "mainChartsSkelHint": "플레이스홀더 — 사용 데이터가 준비되면 Token 차트가 여기 표시됩니다 (전체 캐시 갱신을 기다릴 필요 없음).",
  "serviceBlurb": "<strong style=\"color:rgba(59,130,246,0.8)\">파랑</strong> = 정상 작업. <strong style=\"color:rgba(239,68,68,0.8)\">빨강</strong> = API/서버 스트레스 시간: 공식 장애 <strong>또는</strong> JSONL <code>retry</code>가 로그 타임스탬프 기준으로 분류 (일별 합산이 아님). <strong style=\"color:rgba(251,191,36,0.8)\">노랑</strong> = 클라이언트 장애 <strong>또는</strong> 해당 시간의 JSONL <code>interrupt</code>. <strong style=\"color:rgba(107,114,128,0.6)\">회색</strong> = 작업 없는 장애 시간. Continue/Resume는 정상 작업 시간으로 분류. <strong>누적 막대</strong>는 실제 Token 사용이 있는 시간만 집계 (순수 세션 신호만으로는 막대 시간 미추가). 일별 신호 합계(누적): <strong>Forensic</strong> 섹션 하단 차트. <strong style=\"color:#8b5cf6\">보라색 라인</strong> = Cache Read (우측 축). <strong style=\"color:#22d3ee\">◇</strong> / <strong style=\"color:#4ade80\">▲</strong> = 모델 / Extension 변경일 (클릭 → <strong>슬라이드아웃</strong>: 릴리스 노트, 장애 보고서, Forensic). <strong>툴팁</strong>은 막대/Token 요약만; <strong>Live</strong> 패널: 장애 목록 & Extension 간략 목록.",
  "serviceTooltipSessionSig": "JSONL 라인 (c / r / retry / interrupt)",
  "serviceDS_cleanWork": "정상 작업",
  "serviceDS_affectedServer": "API 장애 중 작업 (Retry)",
  "serviceDS_affectedClient": "클라이언트 버그 중 작업 (Token 영향 없음)",
  "serviceDS_affectedWork": "장애 중 작업",
  "serviceDS_outageOnly": "장애 (작업 없음)",
  "thinkingNote": "⚠ Thinking Token (내부 추론)은 API 응답에 포함되지 않아 여기서 집계되지 않습니다. 세션 Budget에는 포함될 가능성이 높습니다.",
  "tableCols": "날짜|Output|Cache Read|C:O|Overhead|합계|호출|시간|Hit Limit|Sub%|Sub Cache%|Out/h",
  "metaScanError": "스캔 오류: {msg}",
  "reportBtn": "Forensic 보고서",
  "reportTitle": "Forensic 보고서 (Markdown)",
  "reportCopy": "복사",
  "reportDownload": "다운로드 .md",
  "reportCopied": "복사됨!",
  "reportNoData": "데이터 없음 — 스캔이 먼저 완료되어야 합니다.",
  "outageChartTitle": "장애 구간 (status.claude.com)",
  "outageChartBlurbHtml": "막대는 장애 시간 구간(UTC)을 표시합니다. <strong style=\"color:#f97316\">주황</strong> = Major, <strong style=\"color:#ef4444\">빨강</strong> = Critical, <strong style=\"color:#facc15\">노랑</strong> = Minor. 호버하여 상세 확인.",
  "outageDS_spans": "장애 구간",
  "outageAxisHour": "시각",
  "outageTotal": "총 장애 시간",
  "statusPending": "상태…",
  "statusPendingTip": "Anthropic 상태 로딩 중…",
  "statusOutage": "장애 발생!",
  "statusOutageTip": "Anthropic에서 활성 장애 보고됨 (status.claude.com)",
  "statusIncident": "Incident",
  "statusIncidentTip": "오늘 Anthropic에서 Incident가 보고되었습니다 (이미 해결됨)",
  "statusOk": "정상",
  "statusOkTip": "Anthropic에 현재 Incident 없음 (status.claude.com)",
  "tooltipOutage": "장애: ",
  "tooltipModelAdded": "모델 추가: ",
  "tooltipModelRemoved": "모델 제거: ",
  "forensicDS_modelChange": "모델 변경",
  "forensicDS_outageHours": "장애 (h)",
  "serviceDS_versionChange": "Extension 업데이트",
  "tooltipVersionUpdate": "Extension: ",
  "serviceTooltipReleaseClock": "Marketplace/릴리스 시간: ",
  "serviceTooltipReleaseUtc": "UTC 날짜(JSONL 날짜와 동일) 기준: ",
  "serviceTooltipReleaseLocal": "로컬 날짜 (이 머신): ",
  "updateSlideoutClose": "닫기",
  "updateDotAria": "Extension 업데이트: 상세 보기",
  "modelDotAria": "모델 변경: 상세 보기",
  "modelSlideoutHeading": "모델 변경",
  "modelSlideoutNoDetail": "이 날짜의 모델 변경 상세 정보 없음.",
  "updateSlideoutHeading": "Extension 업데이트",
  "updateSlideoutNoDetail": "이 날짜의 버전 상세 정보 없음.",
  "updateSlideoutHighlights": "릴리스 노트 (발췌)",
  "updateSlideoutHighlightsEmpty": "발췌 없음: 스캔 후 서버가 누락된 릴리스를 HTTPS로 ~/.claude/claude-code-releases.json에 보충합니다 — 라이브 업데이트를 잠시 기다린 후 패널을 다시 여세요. 또는 GitHub에서 직접 확인:",
  "updateSlideoutGithubReleases": "GitHub 릴리스",
  "updateSlideoutStatusHeading": "Anthropic 상태 / 장애 (해당일)",
  "updateSlideoutOutageHoursLine": "장애 시간: 총 {total}h (서버 {srv}h · 클라이언트 {cli}h)",
  "updateSlideoutOutageIncidents": "Incident (status.claude.com)",
  "updateSlideoutOutageSpans": "시간 구간 (UTC, 해당 날짜)",
  "updateSlideoutLikelyHit": "참고: JSONL에 Hit Limit 라인이 많음 — 장애와 시간적 연관 가능성 (휴리스틱).",
  "updateSlideoutIncidentStart": "시작",
  "updateSlideoutIncidentResolved": "해결",
  "updateSlideoutIncidentOngoing": "진행 중 / 미확인",
  "updateSlideoutForensicHeading": "Forensic (요약)",
  "serviceTooltipReleaseGithubHint": "GitHub (릴리스 페이지):",
  "timelineTitle": "작업 시간 & 장애 타임라인 (0–24h)",
  "timelineBlurbHtml": "<strong style=\"color:rgba(59,130,246,0.7)\">파랑</strong> = 작업 시간 (첫 활동~마지막 활동 시간, 투명도 = 강도). <strong style=\"color:rgba(239,68,68,0.7)\">빨강</strong> = Anthropic 장애. <strong style=\"color:#22d3ee\">◇</strong> = 모델 변경. 겹침 = 작업 중 장애.",
  "timelineDS_work": "작업 시간",
  "timelineDS_outage": "장애 (status.claude.com)",
  "timelineAxisHour": "시각 (UTC)",
  "proxySummaryLine": "Proxy — {reqs}개 요청 · {errs}개 오류 · Quota 5h: {q5h}% · 7d: {q7d}%",
  "proxySummaryNoData": "Proxy Analytics — Proxy 데이터 없음",
  "proxyNote": "투명 Anthropic Proxy(NDJSON 로그)의 데이터. API 호출별 Rate Limit 헤더, Cache 상태, 지연 시간 및 Token 귀속.",
  "proxyRatelimitTitle": "Rate Limit (Quota 사용률)",
  "proxyRatelimitBlurb": "도넛 = 현재 Quota 사용률. 5시간 윈도우가 항상 병목. 노랑 >50%, 빨강 >80%.",
  "proxyGauge5hTitle": "5시간 윈도우",
  "proxyGauge7dTitle": "7일 윈도우",
  "proxyGaugeRemaining": "잔여",
  "proxyGaugeUsed": "사용",
  "proxyGaugeResetIn": "리셋까지 {h}h {m}m",
  "proxyTokenChartTitle": "Token 비용 분석 (일별)",
  "proxyTokenBlurb": "누적 막대: Cache Read, Cache Creation, Output Token. 표시 Token과 Quota 소비 간 차이 = 보이지 않는 Thinking Token.",
  "proxyLatencyChartTitle": "API 지연 시간 (일별)",
  "proxyLatencyBlurb": "평균, 최소, 최대 응답 시간(ms). 스파이크는 피크 시간 쓰로틀링 또는 서버 부하를 나타냅니다.",
  "proxyCardRequests": "Proxy 요청",
  "proxyCardRequestsSub": "{errs}개 오류 ({rate}%)",
  "proxyCardLatency": "평균 지연 시간",
  "proxyCardLatencySub": "최소 {min}ms · 최대 {max}ms",
  "proxyCardCacheRatio": "Cache Read 비율",
  "proxyCardCacheRatioSub": "{healthy} 정상 · {affected} 영향",
  "proxyCardModels": "모델 분포",
  "proxyCardModelsSub": "{opus} Opus · {sonnet} Sonnet · {other} 기타",
  "proxyCardQuota5h": "5시간 Quota",
  "proxyCardQuota7d": "7일 Quota",
  "proxyDSCacheRead": "Cache Read",
  "proxyDSCacheCreate": "Cache Create",
  "proxyDSOutput": "Output",
  "proxyDSAvgLatency": "평균 지연 시간 (ms)",
  "proxyDSMinLatency": "최소",
  "proxyDSMaxLatency": "최대",
  "proxyHourlyTitle": "시간별 요청 수 (오늘)",
  "proxyHourlyBlurb": "막대 높이 = 해당 시간의 요청 수. 강도는 상대적 부하. 빈 구간 = API 활동 없음. 피크 시간 집중은 Rate Limit 쓰로틀링과 상관될 수 있습니다.",
  "proxyModelTitle": "모델 & 상태 코드 분석",
  "proxyModelBlurb": "좌측: 모델별 요청 수 (막대) + 평균 지연 시간 오버레이 (라인). 우측: HTTP 상태 코드 분포 — 429 = Rate Limited, 5xx = 서버 오류.",
  "proxyInvisibleCostNote": "보이지 않는 비용: {visible}개 표시 Token, {cache}개 Cache Token, 1% Quota당 {perPct}개 표시 Token 사용 — Thinking Token은 여기서 집계되지 않습니다.",
  "proxyDSRequestsPerHour": "요청 수",
  "proxyDSModelRequests": "요청 수",
  "proxyDSModelLatency": "평균 지연 시간",
  "proxyColdStartInfo": "{total}개 요청 중 {cold}개 Cold Start (평균 Cache 비율: {avg}%, 최소: {min}%)",
  "proxyJsonlNoData": "JSONL 데이터 없음 — 비교를 위해 POST /api/claude-data-sync로 로컬 로그를 동기화하세요.",
  "proxyJsonlNoOverlap": "JSONL과 Proxy 로그 간 겹치는 날짜 없음.",
  "proxyJsonlCompare": "{days}일 비교: JSONL {jsonl} vs Proxy {proxy} Token (비율 {ratio}x). >1.5x면 JSONL 중복 의심.",
  "proxyHourlyLatencyTitle": "시간별 지연 시간 (평균 + 최대)",
  "proxyHourlyLatencyBlurb": "파랑 = 평균 응답 시간, 빨강 = 시간별 최대 지연 시간. 특정 시간대 스파이크는 Anthropic의 피크 시간 쓰로틀링을 나타냅니다.",
  "healthScoreTitle": "Health Score",
  "healthScoreSummary": "{score}/10 — 경고 {warns}건, 심각 {crits}건",
  "healthScoreNoData": "Health Score — 데이터 대기 중",
  "healthQuota5h": "Quota 5h",
  "healthThinkingGap": "Thinking Gap",
  "healthCacheHealth": "Cache Health",
  "healthErrorRate": "오류율",
  "healthHitLimits": "Hit Limits/일",
  "healthLatency": "평균 지연 시간",
  "healthInterrupts": "Interrupt/일",
  "healthColdStarts": "Cold Start",
  "healthRetries": "Retry/일",
  "healthFalse429": "False 429 (B3)",
  "healthTruncations": "Truncation (B5)",
  "healthContextResets": "Context Reset (B4)",
  "healthQuotaBench": "Token/1% Quota",
  "healthAnomalStops": "비정상 중단",
  "findingsTitle": "주요 발견 사항",
  "findingsSummary": "총 {total}건 — 심각 {reds}건, 경고 {yellows}건",
  "findingsNoData": "주요 발견 사항 — 데이터 대기 중",
  "findingThinkingGap": "Thinking Token Gap",
  "findingThinkingGapDetail": "JSONL 보고: {jsonl}, Proxy 확인: {proxy}. PRELIM 중복이 JSONL 수치를 부풀림.",
  "findingOverhead": "Token Overhead",
  "findingOverheadDetail": "{days}일간 {total} 합계 vs {output} Output. Cache가 지배적.",
  "findingHitLimits": "Hit Limit",
  "findingHitLimitsDetail": "{days}일간 {total}건의 Rate Limit 도달 (일 평균 {perDay}건).",
  "findingInterrupts": "Interrupt",
  "findingInterruptsDetail": "{interrupts}건 Interrupt vs {hits}건 Hit Limit (비율 {ratio}x). 세션이 지속적으로 중단됨.",
  "findingQuota": "Quota 5h / 7d",
  "findingQuotaDetail": "5h: {q5}%, 7d: {q7}% 사용. {reqs}건 요청, 표시 Output {output}만.",
  "findingPeakDay": "Peak 일",
  "findingPeakDayDetail": "{total} Token, {calls}회 호출, {overhead}x Overhead.",
  "findingRetries": "API Retry",
  "findingRetriesDetail": "총 {total}건 Retry (일 {perDay}건). API 오류로 반복 호출 발생.",
  "findingCacheParadox": "Cache Paradox",
  "findingCacheParadoxDetail": "높은 Cache 비율이 Context 열화를 감춤. Silent Compaction 후에도 Cache Hit는 높게 유지.",
  "healthCollapseSummary": "Health {score}/10 — 경고 {warns}건, 심각 {crits}건 · 발견 사항 {findings}건",
  "filterDateRange": "기간:",
  "filterScope": "차트:",
  "filterHost": "소스:",
  "filterHostAll": "전체",
  "healthHistoryLabel": "Health Score",
  "healthHistoryWarn": "경고",
  "healthHistoryCrit": "심각",
  "incidentHistoryLabel": "Incident & Hit Limit (일별)",
  "incidentDSOutageHours": "장애 (시간)",
  "incidentDSHitLimits": "Hit Limit",
  "incidentAxisOutage": "장애 (h)",
  "incidentAxisHitLimits": "Hit Limit",
  "outageTimelineTitle": "Service Quality (일별 24h)",
  "outageTimelineOk": "없음",
  "availKpiSummary": "핵심 지표",
  "availKpiTotal": "전체 가용성",
  "availKpiPeriod": "기간",
  "availKpiDowntime": "다운타임",
  "availKpiMonth": "월",
  "availKpiIncidents": "Incident",
  "availKpiHours": "시간",
  "availKpiAvail": "가용성",
  "availKpiImpact": "심각도별",
  "availKpiKind": "소스별",
  "uptimeChartTitle": "Service Uptime (일별 24h)",
  "uptimeOperational": "정상 운영",
  "uptimeDegraded": "성능 저하",
  "uptimePartial": "부분 장애",
  "uptimeOutage": "장애",
  "availKpiTrend": "vs. 전월",
  "availKpiCurrent": "(진행 중)",
  "userProfileSummary": "User Profile — {version} · {entrypoint} · 버전 {verCount}개 · 이상률 {rate}% ({anomalies}/{calls}) · 최다 문제: {worst} ({worstCount})",
  "userProfileNoData": "User Profile — 데이터 없음",
  "userVersionHealthTitle": "Version Health",
  "userEntrypointChartTitle": "클라이언트 유형 (Timeline)",
  "userProfileCardVersion": "CLI 버전",
  "userProfileCardEntrypoint": "클라이언트",
  "userProfileCardAnomalyRate": "이상률",
  "userProfileCardWorstVer": "최다 문제 버전",
  "userDSHitLimit": "Hit Limit (429)",
  "userDSRetry": "Retry",
  "userDSInterrupt": "Interrupt",
  "userDSTruncated": "Truncated",
  "userDSApiError": "API Error",
  "userSortAnomalies": "이상 많은 순",
  "userSortNewest": "최신 버전 순",
  "userSortCalls": "호출 많은 순"
}
