apiVersion: v1
kind: Service
metadata:
  name: claude-app
spec:
  selector:
    app: claude-dashboard
  ports:
    - name: http-dashboard
      port: 3333
      targetPort: http-dashboard
      protocol: TCP
    - name: http-proxy
      port: 8080
      targetPort: http-proxy
      protocol: TCP
  type: ClusterIP
